src/renderer/shaders/deferred_directional_light_fs.glsl, src/renderer/shaders/deferred_point_light_fs.glsl, src/renderer/shaders/deferred_spot_light_fs.glsl, src/renderer/shaders/gbuffer_fs.glsl
Fixes compilation on macos 10.15.6
Error without the patch:
`Failed to compile GBufferShader_FragmentShader shader: ERROR: 0:176: Invalid call of undeclared identifier 'texture2D'`
texture2D() is deprecated in favor for texture() as of at least opengl 3.3
=> shaders: texture2D -> texture

examples/3rd_person.rs, examples/async.rs, examples/lightmap.rs, examples/scene.rs, examples/simple.rs, examples/ui.rs
Fixes #32
* handle key inputs via `WindowEvent`s
* (keep handling mouse inputs via `DeviceEvent`s)
Not tested on Windows/Linux.
Off topic: I'm not familar with Git/GitHub, but feel free to squash these commits if you like.
=> Allow key input in examples on macOS (#32)

rg3d-core/src/math/ray.rs, src/renderer/deferred_light_renderer.rs, src/renderer/gbuffer.rs, src/renderer/mod.rs, src/renderer/shaders/deferred_directional_light_fs.glsl, src/renderer/shaders/deferred_point_light_fs.glsl, src/renderer/shaders/deferred_spot_light_fs.glsl, src/renderer/surface.rs, src/resource/fbx/mod.rs
I added specular texture rendering and the fbx loader loads the `SpecularFactor` into a texture.
This pull request might alter the appearance of existing projects. Originally the specular power/exponent/factor was hardcoded to `80`, now it is anywhere between `0` and `255` and by default probably `255`, because I use the white_dummy texture, when no specular texture exists. I'm not sure if this is a reasonable default for this.
=> Add Specular Textures

rg3d-ui/Cargo.toml
the old version didn't work on apple m1 cpus
=> updated sysinfo to 0.16.3

rg3d-ui/src/lib.rs, rg3d-ui/src/widget.rs
This PR implements support for tooltips on `Widget`.  
```rust
scale_mode = ButtonBuilder::new(
WidgetBuilder::new()
.with_margin(Thickness::uniform(1.0))
.with_tooltip(
BorderBuilder::new(
WidgetBuilder::new()
.with_background(BRUSH_DARKER)
.with_foreground(BRUSH_LIGHTER)
.with_child(
TextBuilder::new(
WidgetBuilder::new(),
)
.with_text("Commit Scaling")
.build(ctx),
),
)
.with_stroke_thickness(Thickness::uniform(1.0))
.build(ctx),
)
.with_tooltip_time(1.5),
)
```
The tooltip is shown on hover, and is kept around while the mouse is over the node As well, the tooltip is kept when the mouse is over the tooltip (this would allow for interactable information in tooltips).  
Note #1: In the `UserInterface::update`, I just put it in a spot that seemed alright, unsure if it was best position. …
=> Add tooltips

rg3d-ui/src/lib.rs, rg3d-ui/src/widget.rs
This PR adds support for context menus (closes #81), essentially popups that are shown on right click. Example usage:
```rust
WidgetBuilder::new().with_context_menu(
PopupBuilder::new(WidgetBuilder::new())
.with_content(
BorderBuilder::new(
WidgetBuilder::new().with_child(
TextBuilder::new(WidgetBuilder::new())
.with_text("Testing context menu!")
.build(ctx),
),
)
.with_stroke_thickness(Thickness::uniform(1.0))
.build(ctx),
)
.stays_open(true)
.build(ctx)
)
.build(),
```
Though, I think this would be more useful if `Menu` could be used for this, since often context menus are going to look and act really similar (one appearing at the button, the other at cursor) with both being list of options. Perhaps make `Menu` handle `PopupMessage`s as well?
=> Add Context Menu

rg3d-ui/src/menu.rs
This PR removes the `None` variant from `MenuItemContent`, and replaces the only usage of it with an `Option<MenuItemContent>`.
=> Remove MenuItemContent::None

rg3d-core/src/math/plane.rs, rg3d-core/src/math/ray.rs, rg3d-core/src/pool.rs, rg3d-sound/src/device/dummy.rs, rg3d-sound/src/dsp/filters.rs, rg3d-sound/src/dsp/mod.rs, rg3d-ui/src/lib.rs, src/engine/mod.rs, src/scene/base.rs, src/scene/transform.rs
Fixes:
1. URLs are now hyper links
2. ```[`method`]``` are now linked with ```[`method`](Self::method)```
3. Add `#![doc(unused)]` in `dummy.rs` (sound module)
I left these warnings in `wav.rs`:
---
Hi mr, awesome work! I'm going to get a credit card :)
=> fix `cargo doc` warnings

Cargo.toml, rg3d-core-derive/Cargo.toml, rg3d-core-derive/README.md, rg3d-core-derive/src/lib.rs, rg3d-core-derive/src/visit.rs, rg3d-core-derive/src/visit/args.rs, rg3d-core-derive/tests/basic.rs, rg3d-core/Cargo.toml, rg3d-core/src/visitor.rs
This PR adds experimentals supports for `#[derive(Visit)]`
```rust
use rg3d::core::visitor::prelude::*;
// or: use rg3d_core::visitor::prelude::*;
#[derive(Visit)]
pub struct MyCoolStruct { .. }
```
* `struct UnitStruct;`
* `struct TupleFields(f32, f32);`
* `struct NamedFields { a: f32, b: f32 }`
* `enum ComplexEnum { UnitVariant, TupleVariant(f32, 32), NamedVariant { a: f32,  b: f32 } }`
Generics are also considered. For example, `struct Generics<T> { items: Vec<T> }` implements `Visit` with `where Vec<T>: Visit` clause.
Please run `cargo expand --tests basic` to know what the `Visit` implementations are like :)
<details>
<summary>Old comments</summary>
<details>
<summary>Example</summary>
```rust
// imports both the trait and the derive macro
use rg3d::core::visitor::Visit; …
```
=> Initial support for `#[derive(Visit)]`

rg3d-sound/src/device/dummy.rs, rg3d-sound/src/device/mod.rs
1. Do not define `dummy` device on macOS
2. Let dummy device compile
I'm really not sure why it worked previously on macOS.
=> fix dummy sound device

Cargo.toml
Glutin had a version bump because they updated to the latest winit. Looks like they did some minor changes, but nothing that seems breaking.
Tried running rusty-editor with this change and as far as I could tell it ran fine.
[changelog](https://github.com/rust-windowing/glutin/blob/master/CHANGELOG.md)
[commits](https://github.com/rust-windowing/glutin/compare/9d15e0b...16e0a22)
=> Updated glutin to 0.27

rg3d-ui/src/formatted_text.rs, rg3d-ui/src/text_box.rs
This adds a `with_mask_char` and `with_no_mask_char` to `TextBoxBuilder` and `FormattedText`.
Internally this changes the rendering of `FormattedText` to use a list of `mask_char` instead of `self.text` if the `mask_char` is set.
This does mean that multiline functionality does not work, as `code` is never `\n`, `\r` or a space, which is probably acceptable for password input fields.
=> Add a mask_char to TextBox and FormattedText

examples/2d.rs, examples/async.rs, examples/framework.rs, examples/instancing.rs, examples/simple.rs, examples/terrain.rs, src/engine/framework.rs
The GameState trait doesn't provide a way to exit the game programmatically. This provides a way for the on_tick() method to do that.
=> Provide a way to alter control_flow passed in from the event loop

Cargo.toml, rg3d-sound/src/error.rs, src/engine/error.rs, src/renderer/framework/error.rs
Adds an error implementation using `thiserror` to `FrameworkError`,
`EngineError`, and `SoundError`.
This adds `thiserror` as a dependency.
I tried to base the error messages off of the existing doc comments, so hopefully they should all be correct.
My reasoning behind doing this was so I could avoid using unwrap in various places while using `Framework` and instead use the `?` operator.
=> Add error implementations using thiserror

rg3d-sound/examples/write_wav.rs, rg3d-sound/src/engine.rs
Fixes #152. Added an example of using the new methods to output a wav file.
=> Allow creating SoundEngine without a sound device

Cargo.toml, rg3d-core-derive/Cargo.toml, rg3d-core-derive/README.md, rg3d-core/Cargo.toml, rg3d-resource/Cargo.toml, rg3d-sound/Cargo.toml, rg3d-ui/Cargo.toml, src/lib.rs
Unified the order of fields, added some fields (mainly categories). The new resolver ( https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2 ) shouldn't influence much, in theory it could improve compile times in some situations. I think it's mostly important for binaries but can't hurt to spread awareness of it. Also added icon that will show up on docs.rs, at least for the main crate (bevy does it this way too).
=> Update Cargo.tomls and add icon for docs

src/scene/base.rs, src/scene/camera.rs, src/scene/node.rs, src/utils/behavior/mod.rs
This should make docs CI pass even with `RUSTDOCFLAGS: --deny warnings`. There are still unused field warns in UI but those don't get converted to errors.
=> Fix docs warnings

.github/workflows/ci.yml
This currently fails (at least we know it works properly), the issues are fixed on another MR.
Also, why use windows-2019? Any particular reason? I think i heard that docs on linux can be a bit faster because windows is slower with lots of files but idk if it applies here or if it matters.
=> Fix docs CI

.github/workflows/audit.yml, .gitignore, README.md
Detect vulnerable deps
This should currently fail because there are multiple issues.
In general, some issues are impossible to fix immediately and ok to ignore short term - like warnings that something is unmaintained - there's a flag for ignoring specific advisories - that's better than removing --deny warnings because it makes you notice new warns.
Cargo audit and deps.rs works best when your deps use it too :/
Oh and it runs on a timed schedule so even if you don't touch rg3d for over a week and a new vuln pops up, you'll get notified.
This is in a separate file so it doesn't fail *all* CI and also because we can add another separate badge for this and spread awareness. Which would be awesome.
If i find time tomorrow, i want to try going through some deps and improving their CIs + …
=> Cargo audit CI + badge

README.md
It seems there are 2 ways of specifying the badge:
- `rg3d/actions/workflows/<name of file .yml>`
- `rg3d/workflows/<name of workflow>`
I didn't even know the first existed and mixed it up when copy pasting
=> Fix audit badge

rg3d-core-derive/Cargo.toml, rg3d-core-derive/README.md, rg3d-core-derive/src/inspect.rs, rg3d-core-derive/src/inspect/args.rs, rg3d-core-derive/src/inspect/utils.rs, rg3d-core-derive/src/lib.rs, rg3d-core-derive/src/visit/args.rs, rg3d-core-derive/tests/it/inspect.rs, rg3d-core-derive/tests/it/main.rs, rg3d-core-derive/tests/it/visit.rs, rg3d-core-derive/tests/it/visit/basic.rs, rg3d-core-derive/tests/it/visit/compat.rs, rg3d-core/src/inspect.rs
Closes #186
From [tests/it/inspect.rs](https://github.com/toyboot4e/rg3d/blob/inspect-derive/rg3d-core-derive/tests/it/inspect.rs):
```rust
use rg3d::{
// maybe add `prelude`?
core::inspector::{Inspect, ProprertyInfo},
scene::transform::Transform,
};
#[test]
fn inspect_attributes() {
#[derive(Default, Inspect)]
pub struct Data {
#[inspect(skip)]
skipped: u32,
#[inspect(group = "Pos", name = "Super X")]
x: f32,
#[inspect(expand)]
tfm: Transform,
#[inspect(group = "Pos")]
y: f32,
}
let data = Data::default();
let expected = vec![
PropertyInfo {
name: "Super X",
group: "Pos",
value: &data.x,
},
PropertyInfo {
name: "Y",
group: "Pos",
value: &data.y,
},
];
assert_eq!(data.properties()[0..2], expected);
assert_eq!(data.properties().len(), 2 + data.tfm.properties().len());
}
```
c.f. [Delete …
=> Initial support of `#[derive(Inspect)]`

rg3d-core-derive/src/inspect/utils.rs, rg3d-core-derive/src/lib.rs, rg3d-core-derive/src/visit.rs, rg3d-core-derive/src/visit/utils.rs, rg3d-core-derive/tests/it/main.rs
Hi 👋 It's just some refactoring and _should not_ change any `#[derive(Visit)]` output.
Contents:
* Renaming of variables + moving of functions
* Reducnig some lines of code with `visit::utils::create_impl`
`test_output` did not change after the commits, at least. This is the 2rd and the last refactoring I think 🙏
=> Refactor `#[derive(Visit)]`

examples/ui.rs, rg3d-core-derive/Cargo.toml, rg3d-core-derive/src/inspect.rs, rg3d-core-derive/src/inspect/args.rs, rg3d-core-derive/src/inspect/utils.rs, rg3d-core-derive/tests/it/inspect.rs, src/scene/camera.rs
Closes #189.
<details><summary>example</summary>
```rust
#[derive(Inspect)]
pub struct X {
#[inspect(expand_subtree)]
y: Y,
}
#[derive(Inspect)]
pub struct Y {
a: u32,
}
// expands to
impl Inspect for X {
fn properties(&self) -> Vec<PropertyInfo<'_>> {
let mut props = Vec::new();
props.push(PropertyInfo {
owner_type_id: std::any::TypeId::of::<Self>(),
name: "y",
display_name: "Y",
group: "X",
value: (&self.y),
});
props.extend((&self.y).properties());
props
}
}
impl Inspect for Y {
fn properties(&self) -> Vec<PropertyInfo<'_>> {
let mut props = Vec::new();
props.push(PropertyInfo {
owner_type_id: std::any::TypeId::of::<Self>(),
name: "a",
display_name: "A",
group: "Y",
value: (&self.a),
});
props
}
}
```
</details>
<details><summary>enum example</summary>
```rust
#[derive(Inspect)]
pub …
```
=> Add enum support for `#[derive(Inspect)]`

rg3d-core-derive/src/inspect.rs, rg3d-core-derive/src/inspect/args.rs, rg3d-core-derive/src/inspect/utils.rs, rg3d-core-derive/src/inspect/utils/prop_keys.rs, rg3d-core-derive/tests/it/inspect.rs
Hi 👋  mr! I'm recently impressed by your realtime attack.. can't estimate your love!
Closes #193. The constants _should_ work as expected, but I didn't test (sorry).
- The constants pullute docs 🤔  But I [didn't find any][D] `#[doc(shrink_by_default)]` attribute.
- Property key constants for private fields are exposed (if it matters, another PR can come).
- Note that there's no key constants for expanded (flatten) field properties (since we can't track the expanded type's fields).
[D]: https://doc.rust-lang.org/rustdoc/the-doc-attribute.html
---
By the way, [this line][L] of `examples/inspector.rs` needs one more field. You might know, but just in case :)
[L]: https://github.com/rg3dengine/rg3d/blob/master/examples/inspector.rs#L141
=> `#[derive(Inspect)]`: generate property key constants

.github/workflows/audit.yml
Another XCB advisory, should be safe to ignore - added details to https://github.com/rg3dengine/rg3d/issues/208
=> Ignore RUSTSEC-2020-0097 for now

src/lib.rs
This makes them searchable from the main rg3d docs page
Downside is people are less likely to see the doc comment on the subcrates - for example rg3d_sound has a nice example there. Might be worth at least copy pasting it into the module doc comment, unless there's a better solution.
Also noticed rg3d_physics2d and 3d are not on crates.io yet but the links i added should work after they're published.
=> Reexport subcrates as modules

rg3d-core/src/pool.rs
This allows to iterate through a reference to the pool without calling `.iter()` explicitly, which is sometimes considered more idiomatic.
=> Impl IntoIterator for refs to Pool

.gitignore, .vscode/settings.json
I added a settings file for VSCode which disables a rust-analyzer error which is broken and triggers quite often on nalgebra types.
During that process, i realized the .gitignore contains `.*` - i removed it and instead ignored specific stuff explicitly - i know you use intellij i use vscode so i added those. I hope you don't mind that i copy-pasted a whole bunch of lines, not all of which are related to the project but i have been using https://github.com/github/gitignore for a long time in various projects and never had any issues - i much prefer using a well-tested copy-pasted file than a glob which matches more than it should.
=> Gitignore, vscode

rg3d-ui/src/ttf.rs
My clippy has been reporting these as unused for a long time but CI only started failing recently, probably something got fixed in the new release.
There are still 2 unused fields in the codebase but i am not sure what to do with them so i left them to you.
=> Remove unused structs

rg3d-core/src/profiler.rs, rg3d-core/src/sstorage.rs, src/renderer/batch.rs, src/resource/texture.rs, src/scene/mesh/buffer.rs, src/scene/mesh/surface.rs
I didn't do a thorough check but it looks like none of these hashes survive after engine exit so changing them should be ok. Besides, DefaultHasher doesn't guarantee stable hashes either.
=> Replace DefaultHasher with FxHasher

.github/workflows/ci.yml
Surprise! We haven't been running most tests or lints because nobody added --workspace :/
Also fixes rg3dengine#228
Removing comment about macOS 11 since it's gonna be the default for macos-latest soon: actions/virtual-environments#4060
So now this should find a bunch of new issues, might wanna merge this only after fixing those.
=> Improve CI (matrix, --workspace)

rg3d-core/Cargo.toml
See: https://github.com/rust-lang/futures-rs/issues/2529
As a result `futures = "0.3.18"` is no longer available on crates.io.
```
$ cargo metadata
warning: please specify `--format-version` flag explicitly to avoid compatibility problems
Updating git repository `https://github.com/rg3dengine/rg3d`
Updating crates.io index
error: failed to select a version for the requirement `futures = "^0.3.18"`
candidate versions found which didn't match: 0.3.17, 0.3.16, 0.3.15, ...
location searched: crates.io index
required by package `rg3d-core v0.18.0 (https://github.com/rg3dengine/rg3d#ec581b75)`
... which satisfies git dependency `rg3d-core` of package `rg3d v0.24.0 (https://github.com/rg3dengine/rg3d#ec581b75)`
... which satisfies git dependency `rg3d` of package `game v0.1.0 …
```
=> Futures 0.3.18 has been Yanked

fyrox-core-derive/src/inspect/args.rs, fyrox-core-derive/src/inspect/utils.rs, fyrox-core-derive/tests/it/inspect.rs, fyrox-core/src/inspect.rs, fyrox-core/src/pool.rs
Closes [#285](https://github.com/FyroxEngine/Fyrox/issues/285):
```rust
#[derive(Inspect)]
struct S(#[inspect(is_modified = "Clone::clone")] bool);
```
I personally preferred to allow any path, but changing it to method name is also easy :)
=> add `PropertyInfo::is_modified` #285

src/renderer/framework/geometry_buffer.rs, src/renderer/framework/state.rs, src/renderer/light/mod.rs, src/renderer/mod.rs
Something i ran into while i was trying to quickly get perf info.
In general, libs should make most public types Debug if possible so those types can be effortlessly used as fields in structs that derive Debug.
=> Impl Debug for all Statistics structs

src/engine/mod.rs, src/engine/resource_manager/container/mod.rs, src/engine/resource_manager/mod.rs, src/renderer/mod.rs, src/renderer/renderer2d/mod.rs
As discussed on discord, this is needed to be able to split physics and UI updates.
I also renamed renderer's `update` to `update_caches` to make it clearer what it does (i thought it did more and found it surprising renderer updated before physics).
=> Make everything called from Engine::update public

editor/src/main.rs, examples/README.md, examples/custom_loader.rs, examples/custom_loop.rs, examples/inspector.rs, examples/lightmap.rs, examples/lod.rs, examples/navmesh.rs, examples/save_load.rs, examples/scene.rs, examples/shared/mod.rs, examples/ui.rs, src/engine/framework.rs, src/engine/mod.rs, src/engine/resource_manager/container/mod.rs, src/engine/resource_manager/loader/curve.rs, src/engine/resource_manager/loader/mod.rs, src/engine/resource_manager/loader/model.rs, src/engine/resource_manager/loader/shader.rs, src/engine/resource_manager/loader/sound.rs, src/engine/resource_manager/loader/texture.rs, src/engine/resource_manager/mod.rs
The loaders for the resources can be customized when the engine is created:
- Engine requires the ResourceManager to be created explicitly.
- The default loader and ResourceLoader traits were made public
- Some minor API changes were made on the ResourceLoader to easy its usage
- removed the associated Future type
-  `&self` instead of `&mut self`
- Send for not wasm targets
A new example was added. Later it could be improved to add real loader (ex load model from other file formats)
It seems as this is only a first step because the resource data (ModelData, TextureData etc.) has no functionality yet to create them "by hand".
A next step could be to move the fbx loader into it's own crate and it'd prove that complex scene can be loaded without the need of any internals of the engine. But …
=> Add option to define custom resource loaders

fyrox-ui/src/lib.rs, fyrox-ui/src/ttf.rs
I wanted to make the default font size a little bigger because I had trouble reading it on my screen. I searched the discord and there didn't seem to be a good way to do it yet.
I decided the best way would be to make a `FontBuilder` that also encapsulates the idea of the `DEFAULT_FONT`.
This isn't a general solution to the issue of dynamic font size changes, and font atlases etc. but it might lower the barrier to getting started.
I also changed `Font:: from_memory` to take `Deref<Target = [u8]>` so you don't need to copy it into a `Vec` if you already have the slice. I don't think this will break existing code, but it may give a clippy warning (if they use it) telling them they don't need to call `.into()`.
=> Add FontBuilder

examples/scripting/Cargo.toml
Change makes it so you do:
`cargo build --package scripting`
instead of:
`cargo build --package test_scripting`
=> Change package to scripting

editor/src/absm/canvas.rs, editor/src/asset/item.rs, examples/ui.rs, fyrox-core/src/math/mod.rs, fyrox-ui/src/border.rs, fyrox-ui/src/color.rs, fyrox-ui/src/draw.rs, fyrox-ui/src/grid.rs, fyrox-ui/src/image.rs, fyrox-ui/src/lib.rs, fyrox-ui/src/list_view.rs, fyrox-ui/src/scroll_bar.rs, fyrox-ui/src/scroll_panel.rs, fyrox-ui/src/text.rs, fyrox-ui/src/text_box.rs, fyrox-ui/src/vector_image.rs, fyrox-ui/src/widget.rs, fyrox-ui/src/window.rs
The PR adds support for custom layout and render transform, it could be used to rotate/scale/translate/shear widgets. It is especially useful for things like canvases with zoom/drag features and so on.
=> Add layout + render transform support

fyrox-core-derive/src/inspect/args.rs, fyrox-core-derive/src/inspect/utils.rs, fyrox-core-derive/src/inspect/utils/prop_keys.rs, fyrox-core-derive/tests/it/inspect.rs
Because the hack is not in use today.
Reverting this change is easy.
=> Remove `#[inspect(expand)]` and `#[inspect(expand_subtree)]`

fyrox-core-derive/Cargo.toml, fyrox-core-derive/src/inspect.rs, fyrox-core-derive/src/inspect/args.rs, fyrox-core-derive/src/inspect/utils.rs, fyrox-core-derive/src/inspect/utils/prop_keys.rs, fyrox-core-derive/tests/it/inspect.rs
This PR changes the property key constants for enums generated with `#[derive(Inspect)]`.
Let's consider this code:
```rust
#[derive(Inspect)]
enum E {
A { field: usize },
B { field: usize },
}
```
Before this PR, it generates:
```rust
impl E {
pub const A: &'static str = "field";
pub const B: &'static str = "field";
}
```
After this PR, it generates:
```rust
impl E {
pub const A: &'static str = "A.field";
pub const B: &'static str = "B.field";
}
```
With runtime reflection, we might refer to enum fields like `joint.BallJoint.local_anchor1`.
=> Internal: change property key name to consider enum variant's name

Cargo.toml, editor/src/build.rs, editor/src/lib.rs, editor/src/scene_viewer.rs, editor/src/utils/mod.rs, fyrox-ui/src/button.rs, src/engine/executor.rs, src/engine/mod.rs, src/plugin/mod.rs, src/renderer/ui_renderer.rs
This PR implements full isolation of a game code, instead of running the game in the editor directly the editor now spawns separate process. The PR fixes lots of issues related to shared engine instance between editor and the game and removes some APIs (i.e. `SceneUserInterface`).
=> Isolate running game in separate process

fyrox-core-derive/README.md, fyrox-core-derive/src/inspect.rs, fyrox-core-derive/src/inspect/args.rs, fyrox-core-derive/src/inspect/utils.rs, fyrox-core-derive/src/reflect/args.rs, fyrox-core-derive/tests/it/inspect.rs, src/scene/base.rs, src/scene/camera.rs, src/scene/collider.rs, src/scene/decal.rs, src/scene/dim2/collider.rs, src/scene/dim2/joint.rs, src/scene/dim2/rectangle.rs, src/scene/dim2/rigidbody.rs, src/scene/joint.rs, src/scene/light/directional.rs, src/scene/light/mod.rs, src/scene/light/point.rs, src/scene/light/spot.rs, src/scene/mesh/mod.rs, src/scene/particle_system/mod.rs, src/scene/rigidbody.rs, src/scene/sound/effect.rs, src/scene/sound/mod.rs, src/scene/sprite.rs, src/scene/terrain.rs, src/scene/transform.rs
This PR results in lots of:
```diff
-    #[inspect(getter = "Deref::deref")]
+    #[inspect(deref)]
#[reflect(deref)]
visibility: TemplateVariable<bool>,
```
Changes:
- Add `#[inspect(deref)]`, a shorthand for `#[inspect(getter = "deref()")]`
- `#[inspect(getter = ..)]` now accepts method call syntax, not path
- `#[inspect(is_modified = ..)]` now accepts method call syntax, not path
=> Use simple `#[inspect(deref)]`

fyrox-core-derive/src/reflect.rs, fyrox-core-derive/src/reflect/args.rs, fyrox-core-derive/src/reflect/prop.rs, fyrox-core-derive/tests/it/reflect.rs, fyrox-core/src/reflect.rs
Direct change of fields can break invariant. For example, dirty flag is not synced.
This PR adds `Reflect::set_field` method to perform legal value updates.
User can specify value update method with `#[reflect(setter = ..)]` attribute.
Currently `Reflect::set_field` does not return `Box<dyn Reflect>`.
We might have to add `NodeTrait: Default` boundary to support reflect editor commands.
```rust
pub trait Reflect {
fn set(&mut self, value: Box<dyn Reflect>) -> Result<Box<dyn Reflect>, Box<dyn Reflect>>;
fn set_field(&mut self, field: &str, value: Box<dyn Reflect>) -> Result<(), Box<dyn Reflect>> {
/* ~~~~ */
}
// ~~~~
}
```
New test from `fyrox_core_derive/tests/it/reflect.rs`:
```rust
#[test]
fn reflect_custom_setter() {
#[derive(Reflect)]
pub struct Wrapper<T> {
#[reflect(setter = …
```
=> Add `Reflect::set_field`

Cargo.toml, fyrox-core-derive/Cargo.toml, fyrox-core-derive/src/inherit.rs, fyrox-core-derive/src/lib.rs, fyrox-core-derive/tests/it/inherit.rs, fyrox-core-derive/tests/it/main.rs, src/scene/mod.rs
Closes #354.
- Currently `#[derive(Inherit)]` is only supported for `StructWith { named: Field }`.
- Generics are also considered.
- Adding support for tuple structs and enums are not much hard. Call me when needed!
=> Add `#[derive(Inherit)]`

fyrox-core-derive/src/reflect.rs, fyrox-core-derive/src/visit.rs, fyrox-core-derive/src/visit/utils.rs
This is an internal clean up PR. Hopefully it can also improve the compile time a bit.
From Twitter:
- [MiniJinja author said](https://twitter.com/mitsuhiko/status/1574111459361132549) avoiding `?` improved both the compile time and the runtime performances.
- [dtolnay said](https://twitter.com/davidtolnay/status/1574266317762224128) they don't use `?` operators in `serde` and `serde-json` "because it is too slow".
- [serde has their own `try!` macro](https://github.com/serde-rs/serde/blob/master/serde_derive/src/try.rs) that avoids type conversion
- [Relevant issue on the rust repo](https://github.com/rust-lang/rust/issues/37939)
=> Remove `?` operators from proc-macro generated code

template/src/main.rs
Note: I made this change through githubs own UI so... no checks at all from my side. I just noticed that the Cargo.toml file that got generated had one too many double quotes and decided to find and purge the extra one.
=> fix extra double quote

README.md
As I described in https://github.com/FyroxEngine/Fyrox/issues/325#issuecomment-1271196758 this should help any Linux user find the correct postfix of those libraries.
=> improve dependency explanation.

src/material/shader.rs, src/material/standard/standard-two-sides.shader
A standard two-sides shader (backface-culling disabled) is very useful
in 3D games. Many objects can be just a plane, such as a flag, tree
leaf, grass, banner, etc.. Here I add a standard two-sides
shader. Almost everything is same as a standard shader, but with
cull_face setting to None.
=> Add a Standard Two-Sides Shader

src/scene/collider.rs, src/scene/dim2/collider.rs, src/scene/dim2/physics.rs, src/scene/graph/physics.rs
This PR adds support for Rapier3d's  [intersection check](https://rapier.rs/docs/user_guides/rust/advanced_collision_detection/#the-intersection-graph)). This is needed to be able to use colliders which are in sensor mode. The existing `Collider::contacts()` only provides collisions on two non-sensor colliders.
This PR adds a new method `Collider::intersects()` to both the 2d and 3d Collider and adds respective unit tests.
=> Add support for Collider intersection check

src/utils/astar.rs
Current implementation of A* assumes, that all vertexes on the map have the same difficulty to reach them. This is not the case, when, for example, some RTS troops are traveling on different types of terrain, like grass, ice or sand. It would be nice to manipulate the "reachability" of vertexes.
My idea of application of such modifier is to expand the formula of g_score calculation to include `difficulty` parameter stored in neighbor `PathVertex` object as a multiplier of distance between current vertex and neighbor. This can be used in dynamic changes of the environment, followed by rebuild of pathfinder.
=> `PathVertex::g_score` penalty for `astar.rs`

editor/src/lib.rs
Currently the audio panel in the editor is not a Tile, small change to make it a tile to enable docking.
=> Bugfix - Made audio panel in editor a Tile

src/engine/executor.rs, src/engine/mod.rs
A 'frame' in fyrox can be oversimplified into the three parts that I care about here:
- Use `user_interface.poll_message()` and pass results to plugins
..do some other stuff..
- Use `user_interface.poll_message()` again to clear any potential messages sent recently
- Draw frame
Now this is fine about half of the time, when a message is sent:
<-- here
First `poll_message()`
..do stuff..
Second `poll_message()`
<-- or here
But if a message is sent during the 'do stuff' part, since the second `poll_message()` (in `src/engine/executor.rs`) doesn't actually do anything with the message recieved, only the widget(s) involved recieve the message, and the plugins don't.
I found this problem in that my buttons were only sending `on_ui_message` about half of the time, while still changing colour. …
=> Fixes messages not being passed to plugins

editor/src/lib.rs, examples/custom_loader.rs, examples/custom_loop.rs, examples/inspector.rs, examples/lightmap.rs, examples/lod.rs, examples/scene.rs, examples/shared/mod.rs, examples/ui.rs, examples/wasm/src/lib.rs, fyrox-sound/src/device/dummy.rs, fyrox-sound/src/device/mod.rs, fyrox-sound/src/engine.rs, src/engine/executor.rs, src/engine/mod.rs
Related to #222 - see latest comment.
I am not sure if the field should be named headless because it just disables sound, not graphics but i figured if adding this field is gonna be a breaking change, might as well call it that so that when somebody figures out a way to disable window creation, it's not another breaking change later.
Basically i thought i'd need to implement a full headless mode but for my usecase (running on CI) it turns disabling sound is all that's needed. I currently don't have any intention of looking into how to implemented a full headless mode because i suspect it would be a lot of effort. Nonetheless, i think this PR is very useful to be able to run fyrox games on CI, the only issue for me is whether i should keep calling that field `headless` or change the name …
=> Minimal support for headless mode

template/src/main.rs
The `fyrox-template script` utility generates an invalid code that cannot be compiled.
```
❯ cargo run --package editor --release
Compiling my_game v0.1.0 (/home/user/test/my_game/game)
error[E0412]: cannot find type `FieldInfo` in this scope
--> game/src/my_script.rs:10:17
|
10 | #[derive(Visit, Reflect, Default, Debug, Clone)]
|                 ^^^^^^^- help: you might be missing a type parameter: `<FieldInfo>`
|                 |
|                 not found in this scope
|
= note: this error originates in the derive macro `Reflect` (in Nightly builds, run with -Z macro-backtrace for more info)
For more information about this error, try `rustc --explain E0412`.
error: could not compile `my_game` due to previous error
```
This patch fixes the auto-generated code.
=> Add a missing reference to the script template

Cargo.toml, editor/src/absm/blendspace.rs, editor/src/absm/command/blend.rs, editor/src/absm/command/mod.rs, editor/src/absm/mod.rs, editor/src/absm/node.rs, editor/src/absm/state_viewer/context.rs, editor/src/absm/state_viewer/mod.rs, editor/src/inspector/editors/mod.rs, fyrox-core/src/math/mod.rs, fyrox-core/src/reflect/std_impls.rs, src/animation/machine/node/blendspace.rs, src/animation/machine/node/mod.rs, src/animation/machine/parameter.rs
This PR adds support for 2-dimensional blend spaces. Blend space allows you to blend any number of animations using a single sampling 2d-vector parameter. They're especially useful for locomotion animations when you need to blend multiple animations into one depending on speed and direction of a character. An example of blend spaces could be found in Unreal Engine [docs](https://docs.unrealengine.com/4.27/en-US/AnimatingObjects/SkeletalMeshAnimation/Blendspaces/Overview/)
=> Blend space

editor/src/menu/view.rs
This pull request is focused on changing the "Sidebar" option to "Inspector" as that is the title of the widget and what we seem to be calling that section in documentation shown here "https://fyrox-book.github.io/fyrox/ui/inspector.html". In addition it changes some of the variable syntax from "sidebar" to "inspector". 
Ultimately this is a fairly minor change that is focused on trying to make the text in the view drop down correspond to the widget involved and change the sidebar variable name to be the widget involved similar to other variables.
=> Changed sidebar to be inspector in the view dropdown menu

editor/src/inspector/editors/mod.rs, editor/src/inspector/handlers/node/mod.rs, editor/src/interaction/terrain.rs, editor/src/menu/create.rs, editor/src/scene/commands/terrain.rs, examples/terrain.rs, fyrox-core/src/variable.rs, src/renderer/batch.rs, src/resource/texture.rs, src/scene/graph/physics.rs, src/scene/terrain.rs
This PR refactors terrain, so it can be resizable:
1) It is now possible to change terrain size at runtime - you can add chunks from any side. This way any terrain can be extended from any side to add new parts of your game world
2) Height map size can be changed - it will be resampled to the new size.
3) Layer blending mask size can now be changed - like the height map, it will be resampled to the new size as well.
=> Terrain refactoring

src/scene/graph/mod.rs
This method is helpful on senerio like putting a nail into a wood, or arrow hitting a target and stuck into the target.
=> Method to link nodes while keeping child's global position and rotation.

template/src/main.rs
Change made due to [logger changing location](https://github.com/FyroxEngine/Fyrox/commit/0a05c4eecd9952c208905bb6d70f936350a43a02). The editor fails without this change.
=> log location changed; fixing editor

editor/src/lib.rs, editor/src/menu/file.rs, editor/src/message.rs, editor/src/scene/mod.rs, editor/src/scene_viewer.rs, fyrox-ui/src/tab_control.rs
This PR adds an ability to open multiple scenes in the editor, each scene will have its own tab in the Scene Viewer. This should significantly improve usability in complex projects with many prefabs.
=> Ability to open multiple scenes in the editor

editor/Cargo.toml, editor/src/world/mod.rs
Hi.
It fix for #372.
For example, now you get "Cylinder" for filters "cilinde", "culunder", "zylin" and so on.
=> improve search in World Viewer

src/scene/mesh/buffer.rs
Hi,
I found a memory-safety/soundness issue in this crate while scanning Rust code for potential vulnerabilities. This PR contains a fix for the issue. 
https://github.com/FyroxEngine/Fyrox/blob/af36a53e01d3b75c203bfc33daee6f103ed0dc49/src/scene/mesh/buffer.rs#L515-L521
If a panic happens within `Vec::<u8>::from_raw_parts()`, the `std::mem::forget(data)` will create a double free vulnerability.
In Rust, `std::mem::forget` does not actually free the memory, instead it simply allows the memory to leak. This can lead to double free when the data object goes out of scope and its destructor is called automatically. The issue arises because, while `std::mem::forget(data)` prevents the destructor of data from being called, the Vec<u8> created from the raw parts still has its own destructor. When …
=> Fixing Potential Double Free Issue

.vscode/settings.json
Hi.
Sometimes developers forget to format code before committing.
These settings will help avoid this problem for vscode users.
=> Add code actions on save in settings.json

fyrox-ui/src/file_browser/menu.rs, fyrox-ui/src/file_browser/mod.rs, fyrox-ui/src/menu.rs, fyrox-ui/src/popup.rs
`FileBrowser` widget does not have any ability to rename/delete/make folders/etc. This PR aims to fix that by adding a context menu with the most common FS actions.
=> Context menu for `FileBrowser` widget

editor/src/audio/mod.rs, editor/src/command/universal.rs, editor/src/inspector/editors/mod.rs, editor/src/scene/property.rs, examples/lod.rs, fyrox-core-derive/tests/it/reflect.rs, fyrox-core/src/reflect.rs, fyrox-sound/src/bus.rs, fyrox-sound/src/effects/mod.rs, fyrox-ui/src/inspector/editors/array.rs, fyrox-ui/src/inspector/editors/collection.rs, fyrox-ui/src/inspector/editors/inherit.rs, fyrox-ui/src/inspector/editors/mod.rs, fyrox-ui/src/inspector/mod.rs, fyrox-ui/src/lib.rs, fyrox-ui/src/message.rs, src/animation/machine/state.rs, src/renderer/batch.rs, src/resource/fbx/mod.rs, src/scene/base.rs, src/scene/mesh/mod.rs, src/scene/mesh/surface.rs, src/scene/node/mod.rs, src/scene/particle_system/mod.rs
=> Use registered property editors to generate editors for collection items (`Vec<T>` + `[T; N]`)

editor/src/absm/mod.rs, editor/src/animation/mod.rs, editor/src/audio/preview.rs, editor/src/camera/mod.rs, editor/src/camera/panel.rs, editor/src/lib.rs, editor/src/particle.rs, editor/src/plugin.rs
This PR significantly reduces PC resources consumption by the editor by stopping its update loop when there's in messages from the OS or there's no user actions. Preview mode keeps the editor updating every frame, which is acceptable since it is not used very often.
=> Optimize PC resources consumption in the editor

README.md
To have faster/easier learning curve and not go through docs, would be nice to have README explain how to get started
=> Add quick start cmd in README.md

src/material/shader/standard/standard-two-sides.shader, src/material/shader/standard/standard.shader, src/material/shader/standard/terrain.shader, src/renderer/framework/shaders/shared.glsl, src/scene/mesh/mod.rs
- Fixes TBN - binormal vector was facing opposite direction
- Fixes parallax mapping - normal vector was used incorrectly, because all calculations performed in TBN space, but normal vector was in world space.
- Improved parallax mapping by adding parallax scaling and parallax center. Parallax center is used for height maps that has baseline other than zero
Fixes #71
=> Graphics fixes

fyrox-ui/src/ttf.rs
I am working on a game remake which uses a non-standard bitmap font format, this change makes the fields of the font structure public so that it can be created manually from its components (For custom formats that have access to all the required fields and can directly set the glyph and tex data where the texture atlas is already created)
- Made the fields of "Font" from fyrox-ui/src/ttf.rs public so they can be created manually like "FontGlyph"
I've attached my usage of this below where I already have the font texture atlas and just directly create the fields (Sorry about the code quality in the screenshot its basically my minimal viable product for getting fonts to render):
=> Expose font fields publicly for manual creation

template/src/main.rs
Quality of life feature that checks whether the directory a project template will be initialized in either doesn't exist or is empty so that users don't accidentally override files if they create a project with a already used name (Adding this because I accidentally did it)
- Warn user if they try to create a project in an existing non-empty directory
- Added --overwrite flag to bypass this check and create in the directory anyway
=> Template init exists checking

editor/src/absm/canvas.rs, editor/src/absm/state_graph/context.rs, editor/src/absm/state_graph/mod.rs
This is similar to my previous pr but the problem that @mrDIMAS found were solved.
**Enhancements made in the ABSM editor:**
- There is a menu added in the node context menu of the absm editor named **Create transition to all nodes** which will create transition from the source node to all states.
- In the state graph viewer similar menu is added which will connect all nodes.
Hope that this will save time while blending animations.
If any problem is found please comment me.
=> Enhancements in the absm editor

editor/src/interaction/terrain.rs, editor/src/scene/commands/terrain.rs
There is a bug while editing the terrain's mask. The editor crashes when invalid terrain mask is entered. This bug is solved.
=> Fixed a small terrain bug

editor/src/settings/mod.rs
- serialization of settings was replaced with file::write_all and ron::ser::to_string_pretty to prevent memory leaks on linux
- this should also make editor run smoother and limit few lags eg. during moving a mesh around
=> github #559 fix for linux memory leaks

editor/src/lib.rs, editor/src/world/mod.rs, fyrox-ui/src/draw.rs, fyrox-ui/src/formatted_text.rs, fyrox-ui/src/lib.rs, fyrox-ui/src/text.rs, fyrox-ui/src/text_box.rs, fyrox-ui/src/ttf.rs, src/renderer/ui_renderer.rs
This PR adds support for dynamic font atlases which removes `height` parameter from fonts and gives access to all glyphs in a font on demand. An atlas (for a particular glyph size) will automatically be updated and a requested glyph will be rendered and packed in the atlas. Each atlas is split into a multiple number of pages to bypass texture size limitation on some GPUs.
This PR also adds an ability to specify text height for both `Text` and `TextBox` widgets, allowing you to use a single font for any character size.
=> Dynamic font atlas

editor/src/lib.rs, template/src/main.rs
With this change it is possible, to load multiple scene at editor's start up.
So you don't need to load all your needed scenes after start manually
=> Allows to start multiple scenes at editor start up

editor/src/highlight.rs
Fixes this error on macos
```sh
[ERROR]: Failed to compile EdgeDetectShader_FragmentShader shader: ERROR: 0:398: Use of undeclared identifier 'gl_FragColor'
thread 'main' panicked at editor/src/highlight.rs:163:62:
called `Result::unwrap()` on an `Err` value: ShaderCompilationFailed { shader_name: "EdgeDetectShader_FragmentShader", error_message: "ERROR: 0:398: Use of undeclared identifier 'gl_FragColor'\n" }
```
I couldn't even run the editor on macos with it using `gl_FragColor`.  This patch lets it run just fine.  AFAIK `gl_FragColor` was deprecated in OpenGL 3.0.  Layout defined at the top of the shader same as the vertex shader below it.
I would assume that windows/linux compiled but threw a deprecation warning before, but I don't have a machine to test that atm.  If so, this would …
=> Use layout instead of the deprecated gl_FragColor

fyrox-ui/src/file_browser/mod.rs
Change:
#[allow(clippy::blocks_in_if_conditions)] 
to newer:
#[allow(clippy::blocks_in_conditions)]
=> fix clippy error in master branch

src/scene/terrain/mod.rs
There's an apparent bug where the x height_map_size wasn't referenced, instead y was referenced twice. I had a heightmap where x < y, causing this issue to become apparent when the heightmap is modified. I didn't see any open issue or instructions that I need to open an issue first, so I just opened the PR. I'm newly unemployed, so if there's a process I'm missing please let me know. I will likely have more PRs and issues to contribute soon.
=> Fixing double pixel loop. It was looping over y twice.

fyrox-ui/src/menu.rs
Attempting to create a MenuItem in the UI editor will crash the editor (since the `MenuItemBuilder.content` is none). This PR only links the content if the content exists.
Edit: Seems to effect stable 0.33.1 too.
=> Fix creating a MenuItem in editor

editor/src/menu/mod.rs, fyrox-ui/src/menu.rs, fyrox-ui/src/messagebox.rs
Just added a couple of UI changes to make it feel more consistent. Some of these changes may be considered more stylish compared to others, so feel free to pick and choose.
Changed:
* MenuItemContent::Text is vertically centered (applies to all popups in the editor)
* Editor Toolbar items are both Vertically and Horizontally centered
* Popup Arrows get a slight margin from the edge of the MenuItem
Original: 
Updated:
* Added margins to messageboxes.
Original: 
Updated:
=> Slight UI Improvements

editor/src/export.rs, fyrox-animation/src/lib.rs, fyrox-animation/src/value.rs, fyrox-dylib/Cargo.toml, fyrox-impl/Cargo.toml, fyrox-impl/src/engine/mod.rs, fyrox-impl/src/resource/gltf/animation.rs, fyrox-impl/src/resource/gltf/gltf_standard.shader, fyrox-impl/src/resource/gltf/iter.rs, fyrox-impl/src/resource/gltf/material.rs, fyrox-impl/src/resource/gltf/mod.rs, fyrox-impl/src/resource/gltf/node_names.rs, fyrox-impl/src/resource/gltf/simplify.rs, fyrox-impl/src/resource/gltf/surface.rs, fyrox-impl/src/resource/gltf/uri.rs, fyrox-impl/src/resource/mod.rs, fyrox-impl/src/utils/astar.rs, fyrox/Cargo.toml
This is a loader for glTF files that looks for .gltf and .glb file extensions and loads models using the gltf crate.
It adds three features to fyrox, fyrox-impl, and fyrox-dylib:
- gltf: Enable the dependency on the gltf crate and enable the loader which depends upon it, including the gltf module in fyrox_impl::resource.
- gltf_blend_shapes: Enable glTF blend shapes, which the glTF format calls "morph targets." Loading morph targets requires enabling the "extras" feature in the gltf crate, and this feature controls whether that is enabled and whether the loader looks for blend shapes.
- mesh_analysis: Causes the glTF loader to search every loaded triangle for zero-length edges and log an error if they are found.
=> glTF Model Loader

fyrox-ui/src/scroll_bar.rs, fyrox-ui/src/scroll_viewer.rs
#199 
Added code to make the `indicator` (thumb) size of the scrollbar adaptive to the `ScrollViewer`. Behavior shown below:
https://github.com/FyroxEngine/Fyrox/assets/120047549/09f05263-d381-44eb-bd9a-a2d5a93085e4
I hope the behavior is as expected. But there is an issue:
It seems to be working fine when the container is extended, but when it is shrunk below a certain size, the indicator's movement gets offset by a certain distance (can be seen in the video where the indicator doesn't touch the top arrow and extends below the bottom arrow)
Any help with this would be greatly appreciated. I hope this helps
Also, I have set the minimum size of the indicator to 15. Please let me know if this should be changed or handled differently.
=> added code to make indicator size adaptive

fyrox-core/src/variable.rs, fyrox-ui/src/dock/tile.rs, fyrox-ui/src/window.rs
I have adjusted when and where the cursor icon changes when interacting with windows.
* I have made it so that the splitter between docked windows always has the resize cursor icon instead of only sometimes. The issue was that the icon was only set by the TileBuilder, so whenever a tile was updated later the cursor icon was not updated. Now it is.
* I have made it so that resize cursor icons never appear when dragging a window. We are not resizing; we are moving, so a resize cursor icon is confusing.
* I have made it so that when a grip is being dragged, the window keeps the resize cursor icon until the drag is released. Otherwise it has the visual appearance of the drag already being released just because the mouse moved ahead of the edge of the window while dragging.
* While trying to …
=> Window user experience improvements and bug fixes.

fyrox-core/src/sstorage.rs, fyrox-ui/src/inspector/editors/immutable_string.rs, fyrox-ui/src/inspector/editors/inspectable.rs, fyrox-ui/src/inspector/editors/mod.rs, fyrox-ui/src/inspector/mod.rs
In my project to create an editor for ImmutableString, I needed to learn to understand the inspector module. To help with this, I added documentation to many undocumented elements of that module. These comments were written by someone who was struggling to understand the design of the inspector module, and so hopefully they can be helpful to other people who might struggle to understand.
This also means that there may be mistakes in the documentation. I would be eager to see those mistakes corrected or the documentation expanded even further, so that I can see what I failed to understand from studying the module.
=> Expanding documentation for inspector module and adding ImmutableString editor.

fyrox-ui/src/inspector/mod.rs, fyrox-ui/src/lib.rs, fyrox-ui/src/menu.rs, fyrox-ui/src/message.rs, fyrox-ui/src/popup.rs
I have created another way to allow a widget to handle the events of popups that it opens by having the Popup widget clone the events of its children into a PopupMessage::Event(UiMessage) message.
I modified the context menu code so that when a context menu is opened, the owner of that popup is automatically set to be the widget that was under the right-click. Particularly, the widget being clicked on is the owner, not the widget that has the context menu, because sometimes the particular child that was under the mouse at time may be important information that should not be forgotten, and regardless the events will still bubble up to the widget that has the context menu.
I fixed the issue that was causing context menus to panic when they close. This was an unrelated issue, but fixing it …
=> PopupMessage::Event system for copying events from Popups to their owners.

fyrox-core-derive/src/lib.rs, fyrox-core/src/variable.rs, fyrox-core/src/visitor.rs
In order to better understand the Visitor struct and Visit trait, I have created documentation for many undocumented items, mostly in visitor.rs. Hopefully this will help anyone who is looking to understand Fyrox serialization better.
I have also studied the derive macro for Visit and I believe I have correctly produced some examples of the sorts of implementations that the macro produces. Please correct me if I have made any mistakes.
=> Visitor documentation.

fyrox-ui/src/text_box.rs
I think it is an ergonomic improvement to have the text of a TextBox be automatically selected when the TextBox gains focus through tab navigation.
=> Auto-select text on focusing TextBox

fyrox-ui/src/inspector/editors/immutable_string.rs, fyrox-ui/src/inspector/editors/string.rs, fyrox-ui/src/numeric.rs, fyrox-ui/src/text_box.rs
Tabbing through an inspector should not cause the inspected object to change. To prevent this, I have created TextCommitMode::Changed which causes a record to be kept of the previous value of the field and refuses to acknowledge any editing to the field unless the result is different from the previous value.
I have modified the String property editor and ImmutableString property editor to use the new commit mode. I have also modified NumericUpDown to use the new commit mode, and modified the way that NumericUpDown parses its text to ensure that if the parsed value of the text does not change, then no change is acknowledged. This means that changing the number of 0s after the decimal point can never accidentally trigger an unwanted change in the value.
NumericUpDown was manually handling …
=> Preventing TextBox and NumericUpDown from sending change messages when they have not really changed.

fyrox-animation/src/lib.rs, fyrox-core/src/lib.rs, fyrox-core/src/sstorage.rs, fyrox-impl/src/scene/base.rs, fyrox-ui/src/dock/config.rs, fyrox-ui/src/widget.rs
I have replaced the String names with ImmutableString names. In the process, I added several enhancements to ImmutableString. I added `From<String>` support to allow ImmutableStrings to be created without copying. I have added Serde implementations for ImmutableString, since Serde support is required for FloatingWindowDescriptor and TileContentDescriptor. I have added a `pub use` in the fyrox-core library to simplify using ImmutableString.
I have added tests to confirm that ImmutableStrings created by `From<String>` operate correctly, and testing Fyroxed with these changes reveals no ill effects.
I noticed a potential issue with one of the tests where it asserts a particular value for `entry_count()`, but the actual value of `entry_count()` depends on the order in which the tests are …
=> Changing names of bases and widgets to ImmutableString

editor/src/animation/mod.rs, editor/src/animation/ruler.rs, editor/src/animation/thumb.rs, fyrox-ui/src/curve/mod.rs
I noticed some inconsistencies in the way that the curve editor calculated positions, especially regarding the position of the thumb of the animation editor. In attempting to diagnose this problem, I found that the way that the curve editor transformed positions was very difficult to follow, so I have attempted to simplify this code and clarify it with plentiful comments to remove all confusion.
Transformation calculations were happening independently in multiple places: the curve editor widget, the thumb widget, and the ruler widget for the animation editor. This duplication was probably somehow causing the problems I was noticing, so I have created a new object called `CurveTransform` which encapsulates the calculation of transform matrices for curve editing. By giving each widget one …
=> Improving curve editor transform matrices

editor/src/camera/mod.rs, fyrox-math/src/aabb.rs
I noticed that camera fitting tended to fail with some objects in my scene and I tracked the problem down to how the fitting algorithm excludes certain AABBs as "invalid" when the only problem with them is that they have zero length in one dimension. I think what validity is *really* supposed to check for that an AABB is not negative in any of its dimensions, so I changed the test for positive into a test for not-negative.
=> Changing AABB validity to include zero-size dimensions to allow camera fitting to work with 2D objects.

fyrox-animation/src/spritesheet/mod.rs, fyrox-animation/src/spritesheet/signal.rs
Since Unity and Unreal Engine bind Q to down and E to up, the old key binds in Fyrox seem very counterintuitive. Therefore, I have modified the key binds to make E up rather than down and vice versa.
=> Change Keybinds to Industry Standard

fyrox-core/src/color.rs, fyrox-core/src/lib.rs, fyrox-impl/src/renderer/debug_renderer.rs, fyrox-impl/src/renderer/framework/geometry_buffer.rs, fyrox-impl/src/scene/dim2/rectangle.rs, fyrox-impl/src/scene/mesh/buffer.rs, fyrox-impl/src/scene/mesh/vertex.rs, fyrox-impl/src/scene/particle_system/draw.rs, fyrox-impl/src/scene/sprite.rs, fyrox-impl/src/utils/raw_mesh.rs, fyrox-math/Cargo.toml, fyrox-math/src/lib.rs, fyrox-ui/Cargo.toml, fyrox-ui/src/draw.rs
...and value_as_u8_slice. Updated all related structs to also derive Pod and Zeroable. This should resolve issue 630.
=> chore(630): added Pod trait to array_as_u8_slice... 

fyrox-impl/src/scene/terrain/mod.rs, fyrox-impl/src/scene/terrain/quadtree.rs
I have forced the terrain's quad tree to update whenever the height terrain is modified. To achieve this, I put the quad tree into a mutex and added a u64 modification count to quad tree.
=> Improving update of terrain quad tree

fyrox-impl/src/material/shader/standard/terrain.shader, fyrox-impl/src/scene/terrain/brushstroke/strokechunks.rs, fyrox-impl/src/scene/terrain/mod.rs, fyrox-impl/src/scene/terrain/quadtree.rs
Previously, terrain rendering had no normal data, with normals always pointing directly up. In order to resolve this problem, I have increased the terrain's version number from 1 to 2, and in the new version all height textures have a one-pixel margin with data that is copied from the neighboring chunks. This allows each terrain vertex to calculate its normal value based on the nearby heights.
This required a significant increase in complexity for the terrain shader and the terrain node in order to correctly account for the margins. During this process I have encountered numerous problems and fixed each one, but due to the complexity of the the whole project it is difficult to be totally confident that there are no unknown issues still remaining. At best I can say that everything *seems* …
=> New terrain version with height texture margins and normals in shader

editor/src/interaction/terrain.rs, editor/src/scene/commands/terrain.rs, fyrox-impl/src/material/shader/standard/terrain.shader, fyrox-impl/src/scene/graph/physics.rs, fyrox-impl/src/scene/terrain/brushstroke/mod.rs, fyrox-impl/src/scene/terrain/mod.rs
Introducing holes to the terrain. This involves:
* A new command: `ModifyTerrainHolesCommand` which is almost exactly like `ModifyTerrainHeightCommand`.
* A new brush target `HoleMask`.
* Modifications to the standard terrain shader to allow it to accept the hole mask and to discard pixels within the holes.
* Modifications to how terrain colliders are generated, including ensuring that the collider is aligned with the terrain so long as the collider node is at the same position as the terrain node.
* Modifications to how terrain textures are resizes so that the hole mask texture size is kept synchronized with the height map texture size.
Nothing has been done to help the collider stay in sync with changes to the terrain. That is can be work for a future commit.
=> Terrain holes

editor/src/lib.rs
Probably was broken in the `811a13426ddb808e778c6ac436671eef87aab9af` commit for the #453 issue, but issue still not fixed.
The window_size field is used as the `PhysicalSize` in all other cases.
Editor start with a size greater than a display size if it takes the window size from the `settings.ron`.
Maybe the problem of the #453 what the `logical_size` is [used](https://github.com/FyroxEngine/Fyrox/blob/4c9a41f273d2c82e48528bae7388d81fb16dca5c/editor/src/lib.rs#L2795) for the `user_interfaces` actions when in other places in code the `PhysicalSize` was passed to render related code? What if some of that places also needs in the `LogicalSize` instead of the `PhysicalSize`?
Host PC info:
OS: Windows 11 23H2
Display: 1920x1080 scaling 150%, 2560x1440 scaling 150%
=> fix an invalid editor window size on second startup at the hidpi display

fyrox-ui/src/check_box.rs, fyrox-ui/src/menu.rs, fyrox-ui/src/searchbar.rs, fyrox-ui/src/tab_control.rs, fyrox-ui/src/utils.rs, fyrox-ui/src/vector_image.rs, fyrox-ui/src/window.rs
Helps avoid the use of margins to center vector images and allows most of the other vector images to remain centered (most noticeable in the checkbox and window close button)
=> Ensure vector images have a set size

editor/src/lib.rs, editor/src/settings/windows.rs
**NOTE**: after merging this PR the editor's window will be maximized by default settings at a startup.
=> support a saving/restoring the maximized flag of the editor's window

editor/src/lib.rs, fyrox-impl/src/engine/mod.rs, fyrox-impl/src/plugin/dylib.rs, fyrox-impl/src/plugin/dynamic.rs, fyrox-impl/src/plugin/mod.rs, fyrox-impl/src/script/constructor.rs
`AbstractDynamicPlugin` trait introduced as a contract between engine and dynamic plugins. All dylib-specific code is hidden inside `DyLibPlugin`, the only built-in implementation of the `AbstractDynamicPlugin`.
=> Refactor hot reload to allow custom dynamic plugins besides dylib-based

editor/src/lib.rs, fyrox-impl/src/engine/mod.rs, fyrox-impl/src/plugin/mod.rs
It's necessary to create IM-style "Input" abstraction like [this](https://docs.unity3d.com/ScriptReference/Input.html). To be more precise, fully-functional IM-style Input assumes keeping the state of which button was pressed or released at exactly this frame, which is not possible without the event that either called before all events or after all updates.
=> post_update callback for Plugin

editor/src/asset/item.rs, fyrox-ui/src/expander.rs, fyrox-ui/src/formatted_text/textwrapper.rs, fyrox-ui/src/grid.rs, fyrox-ui/src/tab_control.rs, fyrox-ui/src/tree.rs
I have implemented the WPF algorithm for laying out Grid widgets, including the resolution system for cases that involve some widgets being measured twice in order to determine some column widths.
I have expanded on the documentation for Grid and made the meanings of Strict, Auto, and Stretch more precise. A few grids in the editor were clearly using the wrong dimensions for their rows/columns, and I have made the necessary corrections so that the editor UI is not affected by these changes to Grid.
Part of these fixes to the editor's grid dimensions was fixing the dimensions of AssetItem's grid, and in order to make AssetItem work as it should I had to fix a problem with Text that was inserting some extra blank lines. This no longer happens, and I have added some unit tests that would …
=> Fix for UI layout, including Grid and Text.

editor/src/absm/mod.rs, editor/src/absm/toolbar.rs, editor/src/animation/command/mod.rs, editor/src/animation/mod.rs, editor/src/animation/track.rs, fyrox-animation/Cargo.toml, fyrox-animation/src/lib.rs, fyrox-animation/src/track.rs, fyrox-animation/src/value.rs, fyrox-graph/src/lib.rs, fyrox-impl/src/resource/fbx/mod.rs, fyrox-impl/src/resource/gltf/animation.rs, fyrox-impl/src/resource/model/mod.rs, fyrox-impl/src/scene/animation/mod.rs, fyrox-resource/src/lib.rs, fyrox-ui/src/animation.rs
This PR splits animation in two parts:
1) The animation itself, that holds the required runtime information such as playback time, time slice, track bindings etc.
2) The animation tracks data resource, that holds (mostly) immutable data of animation tracks. This resource could be shared across multiple animations to reduce memory consumption.
=> Animation tracks data resource

editor/src/plugins/inspector/editors/script.rs, editor/src/settings/general.rs
This adds the Zed Editor option into settings. This should work for every OS except NixOS because it defaults to "zeditor" alias.
=> add Zed editor option into editor settings

fyrox-impl/src/scene/tilemap/tileset.rs
I foolishly wrote a method to panic when the obvious correct thing for it to do was to simply do nothing. This PR corrects that and prevents a pointless crash that I have just noticed when executing the `RemovePropertyLayerCommand` for a tile set.
=> Fixing crash on deletion of tile set property layer.

editor/src/plugins/inspector/editors/mod.rs, fyrox-impl/src/scene/graph/physics.rs, fyrox-impl/src/scene/rigidbody.rs
This PR adds `mass_properties_type` variable of `RigidBodyMassPropertiesType` type to the RigidBody and makes it available to edit `center_of_mass` and `principal_inertia` properties in the editor.
Allows to change those properties when the default values are not great, for example when it is required to have center of mass at a known predefined position.
=> Add additional mass properties

editor/src/plugins/tilemap/autotile.rs, editor/src/plugins/tilemap/brush_macro.rs, editor/src/plugins/tilemap/palette.rs, editor/src/plugins/tilemap/panel_preview.rs, editor/src/plugins/tilemap/tile_inspector.rs, fyrox-impl/src/scene/tilemap/brush.rs, fyrox-impl/src/scene/tilemap/mod.rs, fyrox-impl/src/scene/tilemap/tile_source.rs, fyrox-impl/src/scene/tilemap/tileset.rs, fyrox-impl/src/scene/tilemap/update.rs
I have enhanced tile map editing by allowing tile sets and brushes to explicitly work with empty tile handles as if they were actual tiles, so when they are drawn to the tile map they erase instead of adding tiles.
* Tile handle parsing now accepts "empty" as a valid handle.
* The eraser icon is now drawn to represent cells that contain the empty tile handle.
This allows tile map animations to have empty frames without needing to have a transparent tile, and allows autotiling to work when erasing tiles instead of just drawing tiles.
=> Adding empty tiles to tile map brush

editor/src/plugins/tilemap/wfc.rs, fyrox-autotile/src/lib.rs, fyrox-autotile/src/wave.rs, fyrox-impl/src/scene/tilemap/autotile.rs
I have added multi-threading to Wave Function Collapse by creating the `WaveFunctionTaskCommand` that starts a new thread each time the command is executed until the Wave Function Collapse finishes or reaches the maximum attempts. This makes it safe to allow WFC to have a very large maximum number of attempts.
I have also tinkered with how WFC calculates probabilities so that terrains that have a large number of tiles will not be given an advantage over terrains with a small number of tiles. I hope this is an improvement, but WFC is very difficult for me to test due to its random nature. It is difficult for me to be sure that it is working correctly because I am not sure what it *should* do exactly.
I have tried to faithfully re-implement the algorithm from …
=> Multithreaded wave function collapse

editor/src/plugins/tilemap/autotile.rs, editor/src/plugins/tilemap/brush_macro.rs, editor/src/plugins/tilemap/interaction_mode.rs, editor/src/plugins/tilemap/wfc.rs, fyrox-autotile/src/auto.rs, fyrox-autotile/src/wave.rs
There is a cost to having macros on a tile map brush because every time the brush is used to draw on the tile map each macro gets its chance to amend the update. To reduce this cost, I have modified the `begin_update` method to allow macros to determine whether they should be involved in the current tile map draw operation. In the future it may be wise to allow macros to be disabled without deleting them.
I also noticed a flaw in how wave function collapse handles edges. When a tile around the edge of the WFC area had 0.0 probability and was therefore excluded from the WFC, the edge constraining method would cause the entire WFC to fail, because the tile that the edge was set to was an impossible tile, and therefore all possible tiles were eliminated.
To fix this I modified the edge …
=> Improvements to autotiling

editor/src/command/mod.rs, editor/src/plugins/tilemap/autotile.rs, editor/src/plugins/tilemap/brush_macro.rs, editor/src/plugins/tilemap/commands.rs, editor/src/plugins/tilemap/macro_inspector.rs, editor/src/plugins/tilemap/mod.rs, editor/src/plugins/tilemap/palette.rs, editor/src/plugins/tilemap/tile_inspector.rs, editor/src/plugins/tilemap/tileset.rs, editor/src/plugins/tilemap/wfc.rs, fyrox-impl/src/scene/tilemap/autotile.rs, fyrox-impl/src/scene/tilemap/brush.rs, fyrox-impl/src/scene/tilemap/mod.rs, fyrox-impl/src/scene/tilemap/tile_source.rs, fyrox-impl/src/scene/tilemap/tileset.rs, fyrox-impl/src/scene/tilemap/update.rs
I have removed some limitations on Tile Set editing and Brush editing to give the Tile Set editor a more consistent and powerful interface:
* Pages can now be drawn/erased in the page area of the editor just as tiles could already be drawn in the tile area. Select a page or group of pages as a stamp, and then use the drawing tools to draw copies of those pages in the page area, and this will create copies of those pages wherever you draw them, including the whole content of the pages. Prior to this, there was no way to duplicate a page
* Brush macros objects now have methods for moving and copying macro data in tiles and in pages. Formerly, when a tile was moved, copied, or deleted, the associated macro data would not be affected. Now macro data stays with a tile and can be copied with a …
=> Improved Tile Set Editing

editor/src/audio/preview.rs, editor/src/camera/panel.rs, editor/src/lib.rs, editor/src/mesh.rs, editor/src/particle.rs, editor/src/plugins/collider/mod.rs, editor/src/plugins/collider/panel.rs, editor/src/plugins/inspector/mod.rs
This is an experiment to see if the editor is improved by moving some of the little control panel windows into the top of the Inspector. This has several benefits:
* It simplifies the code for this control panels, since they no longer need to manage their windows. This PR reduces the lines of code overall.
* It streamlines the Editor interface for the users, since they no longer need to manage these little windows.
* It resembles the UI of Unity, so it should be familiar to some users.
I considered doing the same with the control panels for Terrain and Tile Map, but I am less convinced this would be a good idea since these windows are larger. Instead I suggest that future work may allow a docking tile to hold multiple windows with tabs to select the currently visible window. This way …
=> Moving control panels to Inspector

editor/src/lib.rs, editor/src/scene/container.rs, editor/src/scene_viewer/mod.rs, fyrox-ui/src/button.rs, fyrox-ui/src/decorator.rs, fyrox-ui/src/tab_control.rs, fyrox-ui/src/wrap_panel.rs
Toward the greater project of allowing more than one window in a dockable tile, I have made some enhancements to TabControl and used those enhancements to improve the editor's scene tabs.
* I made a small but important change to `WrapPanel` that only affects widgets without a fixed size, like tabs. I changed how it measures its children from giving them the size of the panel to giving them infinite size. When a node of variable size is giving a finite space to measure it, it will tend to try to fill that space, and it was causing tabs to grow to the size of the whole control. Giving them infinite size causes the tabs to choose their own most-appropriate size. This does not seem to have broken anything.
* I have changed the `TabControlMessage::AddTab` so that it optionally accepts the UUID …
=> Scene Tabs Improvement

editor/src/plugins/inspector/editors/animation.rs, editor/src/plugins/inspector/editors/resource.rs, editor/src/plugins/inspector/editors/script.rs, editor/src/plugins/inspector/editors/surface.rs, editor/src/plugins/inspector/editors/texture.rs, editor/src/plugins/inspector/mod.rs, fyrox-ui/src/inspector/mod.rs
Due to a recent experience where property editors actually failed due to `EditorEnvironment` being unavailable, I discovered that the way that these editors handle that situation could be improved. When a function returns a `Result` there is no need to panic.
I improved `EditorEnvironment::try_get_from` so that it returns `Result<&Self, InspectorError>` instead of `Option<&Self>`, and this change allows `try_get_from` to more elegantly work in implementations of `PropertyEditorDefinition::create_instance`.
This improves error reporting in the event that `EditorEnvironment` ever fails again, and it also simplifies the error handling overall in editors that use `EditorEnvironment`.
=> Improving error handling for property editors in Fyroxed

fyrox-ui/src/menu.rs
A slight modification to `MenuItem` makes it possible to close a menu by clicking on the menu item that opened it. This is a very common UI convention and users tend to expect it.
=> Close a menu by clicking on the menu item

fyrox-ui/src/lib.rs
This simple change makes is to that when a widget is given a maximum size, this does not prevent the widget from being given infinite available size.
When laying out widgets, infinite size is code for asking the widget to choose its own best size. If we instead give the widget a specific size to fill, then widgets that can resize themselves will tend to fill whatever size we give them. This means that if we want to specify that a widget should choose its best size but must not choose a size bigger than some maximum, the only way to do this is by giving it infinite available size and specifying a finite `max_size`. Unfortunately that was impossible due to the available size being automatically clamped in `measure_node`.
As a result, any node which has a maximum size would tend to …
=> Prevent clamping for infinite available size in UI layout system

editor/src/plugins/tilemap/autotile.rs, fyrox-autotile/Cargo.toml, fyrox-autotile/src/auto.rs, fyrox-autotile/src/lib.rs
Having `fyrox-autotile` depend upon `fyrox-core` was a very convenient way to get some useful libraries like `nalgebra`, but `fyrox-core` is a very large dependency that contains many things that are completely useless to `fyrox-autotile`. In order to make it simpler to use `fyrox-autotile` in non-Fyrox projects, I have removed the dependency upon `fyrox-core` and made it so that `fyrox-autotile` only includes the bare necessary dependencies.
=> Removing dependency on `fyrox-core` from `fyrox-autotile`.

editor/src/asset/mod.rs, editor/src/audio/mod.rs, editor/src/command/panel.rs, editor/src/export.rs, editor/src/plugins/absm/blendspace.rs, editor/src/plugins/absm/mod.rs, editor/src/plugins/absm/state_graph/mod.rs, editor/src/plugins/animation/mod.rs, editor/src/plugins/curve_editor.rs, editor/src/plugins/inspector/editors/spritesheet/window.rs, editor/src/plugins/inspector/mod.rs, editor/src/plugins/tilemap/colliders_tab.rs, editor/src/plugins/tilemap/properties_tab.rs, editor/src/scene_viewer/mod.rs, editor/src/world/mod.rs, fyrox-core/src/sstorage.rs, fyrox-ui/src/dock/config.rs, fyrox-ui/src/dock/mod.rs, fyrox-ui/src/dock/tile.rs, fyrox-ui/src/font/mod.rs, fyrox-ui/src/log.rs, fyrox-ui/src/tab_control.rs, fyrox-ui/src/text.rs, fyrox-ui/src/window.rs
I have created a new variation of `TileContent` called `MultiWindow` that allows multiple windows to be docked in a single tile. I have given each tile a `TabControl` to allow the user to switch which window is currently visible within the tile, and I have added a `tab_label` field to `Window` to control what text is shown on the tab. I have given `tab_label` a value for all the most important dockable windows as far as I am aware. Any window with an empty `tab_label` will have a blank tab.
I have tested to see that this new kind of tile works when saving and loading layouts, and it works when closing a docked window, minimizing a docked window, maximizing a docked window, bringing a docked window to front, opening a docked window from the "View" menu,
There are many various interactions …
=> Docking more than one window in the same tile, using tabs

template-core/src/lib.rs
I have added `#![cfg(target_os = "android")]` and `#![cfg(target_arch = "wasm32")]` to the templates for the Android and wasm executors. This prevents the compiler from trying to compile these libraries when the target is inappropriate.
=> Conditional compilation for wasm and android in template

fyrox-impl/src/scene/dim2/physics.rs, fyrox-impl/src/scene/dim2/rigidbody.rs, fyrox-impl/src/scene/graph/physics.rs, fyrox-impl/src/scene/rigidbody.rs
I have added actions for setting the next kinematic position in both 2D and 3D.
Rapier has methods specifically for giving the user this sort of control over kinematic rigid bodies, and so I have created `ApplyAction::NextTranslation`, `ApplyAction::NextRotation`, `ApplyAction::NextPosition` to parallel the methods of rapier.
I have also changed the condition in `sync_rigid_body_node` to make it possible to sync kinematic rigid bodies.
=> Kinematic Physics Support

fyrox-impl/src/engine/mod.rs
This attempt at fixing [the teleportation bug](https://github.com/FyroxEngine/Fyrox/issues/729#issue-2846142773) is far more elegant and simple, and seems to have no side-effects. We just move the handling of plugins and scripts to *before* the scene update instead of after the scene update.
Scripts and plugins are the part of the game that is most likely to create new nodes, and therefore running them after the update would tend to cause the new nodes to be rendered before the nodes are updated, since the update would not come until the next `AboutToWait` event. This is no longer possible because the scene is updated immediately after the scripts and plugins finish running.
=> Moving plugin and script handling to before node handling

fyrox-core/src/pool/mod.rs
The method `Pool::generate_free_handles` may sometimes be used to predict in advance what handles will be returned by `spawn`. In order for this to be reliable, `generate_free_handles` must always return the same handles in the same order as `spawn`. Previously, `generate_free_handles` accessed the `free_stack` in the opposite order from `spawn`, since `spawn` pops from the stack while `generate_free_handles` used to start from the bottom of the stack. By calling `rev()` on the stack iterator of `generate_free_handles`, I have made `generate_free_handles` match the order of the handles used by `spawn`, and I have written a test to help ensure that they are consistent.
=> Reversing `Pool::generate_free_handles` to match `spawn`

fyrox-impl/src/scene/collider.rs, fyrox-impl/src/scene/dim2/collider.rs, fyrox-impl/src/scene/dim2/physics.rs, fyrox-impl/src/scene/graph/physics.rs
I have attempted to simplify and clarify the usage of colliders with the addition of more extensive documentation comments and additional helper methods. The `active_contacts` and `active_intersects` methods are similar to `contacts` and `intersects` except that they skip pairs where `has_any_active_contacts` is false. `active_intersects` has the additional simplification of just directly returning the intersecting colliders instead of returning pairs.
No change in this PR should have any effect upon existing games. It is purely the addition of more methods and documentation.
=> Documentation and helper methods for colliders

fyrox-graphics/src/gl/program.rs
I discovered a bug in `patch_error_message` that caused it to use an incorrect offset, and I have attempted to make `patch_error_message` more defensive to hopefully eliminate the possibility of any other problems.
The correct offset for the next search is the end of the previous result, not the start of the previous search *plus* the end of the previous result. In principle, for some regexes, the end of the result could be the same as the current offset, if the regex matched a zero-length result, so I ensured that the offset steps ahead by at least one.
=> Fixing potential panic in `patch_error_message`

fyrox-impl/src/scene/graph/physics.rs
The terrain collider previously assumed that it could skip a chunk of that chunk had no hole mask. Instead, it should treat the lack of a hole mask as a fully solid terrain and fill in every cell. This pull request corrects that mistake.
=> Correcting terrain hole mask bug

fyrox-impl/src/scene/mod.rs, fyrox-resource/src/manager.rs, fyrox-resource/src/untyped.rs
I used the [tracing-mutex](https://crates.io/crates/tracing-mutex) crate to temporarily tool the mutexes and discover potential sources of deadlock. I have not included tracing-mutex in this PR since tracing-mutex has performance costs, but I have included the modifications that I made in order to stop tracing-mutex from detecting any problems. Hopefully this will eliminate the deadlocking issue.
=> Protecting against resource deadlock

fyrox-ui/src/utils.rs
A fundamental limitation in the way that widgets are measured is that very limited information may be passed in through `available_size`, and this does not capture all the nuances of what we may want from a widget. A widget has no way of knowing its maximum size, its minimum size, whether it should try to fill a given space or whether it should decide its own best size, because all this information cannot be conveyed in a `f32`
Setting the max size of the width of a tool tip currently does not pass any measurement information to the widgets that are being constrained, which means that the widgets are left to choose their own sizes and only afterward are the widgets forced to be within max size. This means that a `Text` widget that is given a max width will not wrap its content, but will …
=> Fixing cut-off text in tooltips

editor/src/highlight.rs, editor/src/plugins/inspector/editors/mod.rs, fyrox-impl/src/renderer/bundle.rs, fyrox-impl/src/renderer/light.rs, fyrox-impl/src/renderer/mod.rs, fyrox-impl/src/renderer/shadow/csm.rs, fyrox-impl/src/renderer/shadow/point.rs, fyrox-impl/src/renderer/shadow/spot.rs, fyrox-impl/src/scene/base.rs, fyrox-impl/src/scene/collider.rs, fyrox-impl/src/scene/dim2/rectangle.rs, fyrox-impl/src/scene/mesh/mod.rs, fyrox-impl/src/scene/node/mod.rs, fyrox-impl/src/scene/particle_system/mod.rs, fyrox-impl/src/scene/sprite.rs, fyrox-impl/src/scene/terrain/mod.rs, fyrox-impl/src/scene/tilemap/mod.rs
By giving each node a `BitMask` called `render_mask` we can provide fine control over whether a camera renders a particular node by doing a bitwise-and on the `render_mask` of the node and the camera. If the two masks have any set bits in common, then the camera will render the node as normal, but if the bitwise-and results in zero, then the node is treated as invisible.
`BitMask` is part of the collision system, since it is defined in `collider.rs`, but it can be useful for purposes like this beyond just collision. I have added some helper methods to make `BitMask` easier to use.
I have only tested this in 2D since the game that I am working on is a 2D game, but whether a game is 2D or 3D should make no difference to how `render_mask` works. So long as `render_mask` has all bits set, …
=> Using a `BitMask` to control which nodes are visible to each camera

fyrox-ui/src/screen.rs
I missed removing the now unused `auto_scale_ui` flag from #783 before it was merged.
=> Remove unused auto_scale_ui flag

project-manager/src/manager.rs, project-manager/src/settings.rs
For some IDEs (like VSCode-based editors), it is better to open the project's folder rather than just the manifest file. With these changes, I allow the usage of `%MANIFEST_DIR%` for that.
Additionally, I've improved code that replaces argument variables so that it replaces them even if the argument includes extra text besides the variable name. i.e.: if there is an argument with value "test-%MANIFEST_PATH%" currently the `%MANIFEST_PATH%` wouldn't be replaced because it requires the whole string to be equal to the variable's name, but with my changes it would actually be replaced, thus making the variables work in a more generic way.
=> Project manager Open IDE settings improvements

.vscode/launch.json, editor/Cargo.toml, editor/src/asset/mod.rs, fyrox-core/src/visitor/error.rs
Previously, the implementation of "Show in explorer" was windows-centric (using the "explorer" command directly). In this PR, it was changed to use the `opener` dependency, which seems to work on Linux and says to support Windows and Mac as well.
Additionally, added the auto-generated `launch.json` file in the `.vscode` folder which is used by the CodeLLDB debugger to run the project directly on VSCode (please let me know if I should remove this file, but I thought I should add it since it is explicitly not ignored in the `.gitignore` file of the project)
Also includes small fix for documentation error
=> Changed "Show in explorer" to work on other operating systems

editor/src/asset/mod.rs
Fixed a crash when the asset browser uses an empty string as a search query.
The issue was that when `self.selected_item_path` was empty (`== PathBuf::default()`), calling `parent()` would fail.
Tested on Windows 11 (no project):
```bash
cargo run --package=fyroxed
```
Fixes #790 
https://github.com/user-attachments/assets/67580912-04fb-4731-a619-09a42225eb88
=> Fixed crash when an empty string is used in the asset browser search

fyrox-impl/src/scene/camera.rs
Updated `Camera.debug_draw` to ignore the node's scale when drawing its frustum, as scaling a camera node shouldn't affect the frustum.
_N/A_
_N/A_
_N/A_
=> Prevented the camera frustum in debug draw from being scaled

editor/src/camera/mod.rs, editor/src/scene/mod.rs
Improved editor camera focus distance to be less close to the object, effectively allowing the user to view the object they chose to focus.
_N/A_
_N/A_
This is what focusing looks like before and after the change
| Before Change | After Change |
| - | - |
| ![image](https://github.com/user-attachments/assets/4c46f18b-45a5-4aaa-a85e-765a4ffba405) | ![image](https://github.com/user-attachments/assets/fbbd6ac7-b5e5-4fb0-a348-1ecf5bc60111) |
| Way too close to the object to see anything (even closer than z_near) | Slightly further away |
=> Improved focus distance to be less close to the object

editor/src/interaction/gizmo/move_gizmo.rs, editor/src/interaction/gizmo/rotate_gizmo.rs, editor/src/interaction/gizmo/scale_gizmo.rs, editor/src/interaction/move_mode.rs, editor/src/interaction/rotate_mode.rs, editor/src/interaction/scale_mode.rs, editor/src/settings/graphics.rs
Improved gizmos by tweaking:
- Arrow length (for move and scale)
- Arrow thickness (for move and scale)
- Ribbon thickness (for rotate)
Thickness has been made consistent across the board (move, rotate, and scale now use the same thickness).
Exposed gizmo scale to the editor settings (under graphics)
_N/A_
Moved magic numbers (arrow length, thickness, and ribbon thickness) to proper `const` values to document them naturally by naming them.
| Action | Before | After |
| - | - | - |
| Move | ![image](https://github.com/user-attachments/assets/5c1c4623-a293-4391-949c-fb7f5b788d1c) | ![image](https://github.com/user-attachments/assets/521e87a6-429e-4437-b123-0732f2869285) |
| Rotate | ![image](https://github.com/user-attachments/assets/3fd77cde-d686-4e66-9e58-0411eeb60e3f) | …
=> Improved gizmo and exposed scale in editor settings

editor/src/camera/mod.rs, fyrox-math/src/aabb.rs
Following https://github.com/FyroxEngine/Fyrox/pull/795, focusing an object is broken when the object isn't positioned at origin. This is because applying a scale matrix to an AABB not position at the world origin `(0, 0, 0)` changes the center of the `AABB`. 
To avoid that, a proper `scale` function has been added to `AxisAlignedBoundingBox`, to effectively scale the AABB **around** its center, instead of scaling it around the world origin.
_N/A_
_N/A_
https://github.com/user-attachments/assets/22ab46e8-2878-4943-af45-99d69444231f
=> Fixed disfunctional node focus following its latest improvement

fyrox-impl/src/renderer/bundle.rs
This simply fixes an incorrect expectation in the tests. Here is the example of the tests failing: https://github.com/FyroxEngine/Fyrox/actions/runs/14782543715/job/41504440447
Fixes #(issue number)
Write here.
Write here.
=> Small test fix for calculate_sorting_index

editor/src/scene/container.rs
* Interaction modes in the toolbar were displayed in this order:
* Select [1]
* Move [2]
* Scale [4]
* Rotate [3]
* Edit Navmesh [5]
* Edit Terrain [6]
* "Rotate" (Key `[3]`) and "Scale" (Key `[4]`) interaction modes are now ordered properly.
_N/A_
Write here.
_New order_
=> Fixed interaction mode order in the toolbar to follow indices: 1..6

editor/src/scene/commands/terrain.rs
`ModifyTerrainHolesCommand::name()` was set to return `Modify Terrain Height` instead of `Modify Terrain Holes`. This PR fixes that incorrect name.
_N/A_
Write here.
=> Fixed terrain holes incorrect command name

fyrox-ui/src/draw.rs, fyrox-ui/src/formatted_text.rs, fyrox-ui/src/formatted_text/run.rs, fyrox-ui/src/text.rs
A `formatted_text::Run` struct and `RunBuilder` have been added into `fyrox-ui` that represents a style modification to a range of chars within some formatted text. Each run may optionally modify:
* Font
* Brush
* Size
* Shadow enabled/disabled
* Shadow brush
* Shadow offset
* Shadow dilation
Each `FormattedText` now contains a `RunSet` which is a vector of runs. Later runs in the vector are given priority over earlier runs, if two runs conflict.
Added methods: `FormattedTextBuilder::with_run`, `FormattedTextBuilder::with_runs`, `TextBuilder::with_run`, `TextBuilder::with_runs`. The `with_run` method takes a single run and adds it to the end of the list. The `with_runs` method extends the list with runs from the given iterator.
* A markup parser to automatically generate runs.
* Messages …
=> Introducing runs to FormattedText

fyrox-core/src/visitor/error.rs, fyrox-core/src/visitor/mod.rs
`[ERROR]: region does not exist: __ROOT__ > Scene > Graph > Pool > Records > Item120 > Payload > Data > NodeData > Resource > Data > State`
instead of:
`[ERROR]: region does not exists State`
=> include breadcrumb into VisitError:RegionDoesNotExist

fyrox-core-derive/src/lib.rs, fyrox-core-derive/src/script_message_payload.rs, fyrox-impl/src/engine/mod.rs, fyrox-impl/src/script/mod.rs
(breaking change) blanket impl for ScriptMessagePayload replaced with derive macro
- allowing user to override get_dynamic_type(&self) -> DynamicTypeId { None }, which I've added recently to this trait (I forgot about orphan rules, making my change useless),
- also, it will help user to catch error early if he due to coding mistake passed wrong variable to send method. such early error detection is what people like in rust, and probably will like in rust-based engine, accepting additional macro for types as reasonable price
=> (breaking change) blanket impl for ScriptMessagePayload replaced with derive macro

fyrox-ui/src/lib.rs
Unlink did set the desired position based on the screen position, which can be outside the window when the screen resolution is higher then the one of the editor. But `set_desired_local_position()` of `Widget` does expect a local position (based on the resolution of the editor. Hence one has to calculate the local position first before setting the desired position.
Fixes #743 
I am struggling to write a good test for the fix. If you want to have a test for the fix then I would need a hint on how to setup a window that simulates being on a screen with a different resolution.
Before:
https://github.com/user-attachments/assets/4dc7e1ee-f982-403c-8fae-90b984860cea
After:
https://github.com/user-attachments/assets/e4894e6c-4c73-457c-a454-aee8a7d8b804
=> fix: use calculated local instead of screen position when setting new desired position after toggling off a view

fyrox-material/Cargo.toml
Adds the missing license and authors fields to the `Cargo.toml` of `fyrox-material`.
Our `cargo-deny` setup is complaining that this crate doesn't have a license.
=> fyrox-material has no license in Cargo.toml

fyrox-impl/src/scene/dim2/joint.rs, fyrox-impl/src/scene/dim2/physics.rs, fyrox-impl/src/scene/graph/physics.rs, fyrox-impl/src/scene/joint.rs
Added the joint motor functionality from the Rapier library for both 2D and 3D.
The motor functionality is designed for revolute joints and prismatic joints.
Use cases may be motored wheels, roulette wheels, pistons, suspensions, springs, etc.
Specifically, opened up the following interfaces:
Joint::set_motor_force_as_prismatic(...)
Joint::set_motor_torque_as_revolute(...) (2D version: Joint::set_motor_torque_as_ball(...))
Joint::set_motor_target_position_as_prismatic(...)
Joint::set_motor_target_angle_as_revolute(...) (2D version: Joint::set_motor_target_angle_as_ball(...))
Joint::disable_motor(...)
To accomplish these interfaces, a new struct "JointMotorParams" is added to the Joint's fields.
The underlying working principle is in the sync_native -> sync_to_joint_node call, a modified …
=> Added the joint motor functionality from the Rapier library

fyrox-impl/src/scene/dim2/joint.rs, fyrox-impl/src/scene/graph/physics.rs, fyrox-impl/src/scene/joint.rs
Apart from motors for revolute and prismatic joint, a ball joint motor is introduced to simulate a fixed joint that tolerates rotational movement and pulls the rigid body back in all 3 axes.
It can be used along with the prismatic joint motor to simulate an elastic connection between two rigid bodies.
Specifically, the following function is introduced:
Joint::set_motor_resistive_torque_as_ball(...)
It reuses the existing JointMotorParams structure to pass information to the native engine.
Code for calling the native engine is revised accordingly.
For 2D, it is essentially calling set_motor_target_angle_as_ball with target rotation 0 because there is only 1 rotational axis. I put it there anyway for symmetry with the 3D version.
Fixes #(issue number)
The introduced features are fully …
=> Added a ball joint motor as a flexible fixed joint in 2D and 3D

editor/src/scene/mod.rs, fyrox-core/src/variable.rs, fyrox-impl/src/scene/dim2/physics.rs, fyrox-impl/src/scene/graph/mod.rs, fyrox-impl/src/scene/graph/physics.rs
Prior to this PR, there was a bug in `InheritableVariable::visit` that would often result in some values not being read. When `InheritableVariable` writes to a visitor, it puts its value into "Value" and puts its flags into "Flags". When it reads, it can try both to read the value directly from the current node or read the value from "Value". This allows an `InheritableVariable` to be read from a visitor that was created using the inner value.
The bug was that `visit` would first try to visit the inner value directly and if that returned `Ok` then it assumed this was successful and never tried visiting "Value". This is a problem for any type that would produce `Ok` when visiting an `InheritableVariable` node, and `fyrox_impl::scene::graph::physics::IntegrationParameters` is such a type …
=> Correcting InheritableVariable::visit and physics integration parameters `dt`
