FyroxEngine/Fyrox

- examples/sound.rs
- src/engine/resource_manager.rs
* Get resource references before event_loop starts
* Align sounds with animation
> improved sound example

- rg3d-sound/Cargo.toml
- rg3d-sound/src/device/coreaudio.rs
- rg3d-sound/src/device/mod.rs
> Add coreaudio sound device for macOS

- Cargo.toml
- src/utils/astar.rs
Updated the image dep because it was marked as insecure - https://deps.rs/repo/github/mrDIMAS/rg3d .
Also fixed one of the tests, idk how to fix the other one.
> Fix a dep and one test

- rg3d-core/src/pool.rs
This PR adds two new methods to `Pool`: `spawn_with(impl FnOnce(Handle<T>) -> T) -> Handle<T>` and `async spawn_with_async(impl FnOnce(Handle<T>) -> impl Future<Output=T>) -> Handle<T>`.  
They make code which would benefit from knowing its own handle nicer to write:  
```rust
let mut bots: Pool<Bot> = Pool::new();
let enemy: Handle<Bot> = bots.spawn_with(|handle: Handle<Bot>| -> Bot {
Bot::new(scene, resource_manager.clone(), handle)
});
```
The `async` version is for async functions, which are likely a common use case. Such as an enemy which loads a model and animations in its constructor:
```rust
let enemy: Handle<Bot> = bots.spawn_with_async(|handle: Handle<Bot>| async move {
Bot::new(scene, resource_manager, handle, "data/models/monster.fbx").await
}).await;
```
Sadly the async …
> Add spawn_with and spawn_with_async

- rg3d-core-derive/src/visit.rs
- rg3d-core-derive/src/visit/args.rs
- rg3d-core-derive/tests/basic.rs
- rg3d-core-derive/tests/compat.rs
- rg3d-core-derive/tests/utils.rs
> add `#[visit(rename = "..")]` attribute

- examples/shared/mod.rs
- src/renderer/deferred_light_renderer.rs
- src/renderer/mod.rs
- src/renderer/shaders/skybox_fs.glsl
- src/renderer/shaders/skybox_vs.glsl
- src/renderer/skybox_shader.rs
- src/resource/texture.rs
- src/scene/camera.rs
- src/scene/graph.rs
- src/scene/mesh/vertex.rs
There is an implementation of skybox with cubemap (#114) . Tbh, I don't like what `SkyBox::create_cubemap()` function looks like. Maybe your review will help me to find out the way to improve it.
> Skybox cubemap

- examples/wasm/index.html
- examples/wasm/main.js
- examples/wasm/styles.css
Addresses: https://github.com/rg3dengine/rg3d/issues/99
Chrome needs user interaction to enable sound, added an animated/transition button to launch the demo for the heck of it.
> WASM start game by user interaction to enable sound

- rg3d-sound/README.md
- rg3d-sound/src/effects/reverb.rs
There was a typo in docs and README.
> Fixed a typo in the sound section.

- rg3d-core/src/pool.rs
I found the message confusing, this makes more sense IMO.
> Improve panic msg

- rg3d-core/src/pool.rs
Related to #233
Using u32 makes more sense here since i am serializing the index and sending it over the network as u32 anyway, no need to roundtrip through usize.
I checked `usize::try_from(index).expect("Couldn't convert index to usize")` in godbolt and it compiles to the same thing as `as` on 32/64 bits (whichever godbolt uses, idk). It probably compiles to something ugly and slow on 16 bits but i don't think rg3d could run on something like that at all. The point is to avoid the `as` keyword because it's dangerous.
I'd like to switch more of Pool's API (at, at_mut, handle_from_index) to `u32` instead of `usize` over time but that might need changes in other parts of the code, these methods are only used by me afaik for now.
> Use u32 in Pool::spawn_at

- .idea/.gitignore
- .idea/inspectionProfiles/Project_Default.xml
- .idea/modules.xml
- .idea/rg3d-core.iml
- .idea/runConfigurations.xml
- .idea/vcs.xml
- examples/grid.rs
- rg3d-ui/src/grid.rs
> Grid optimization

- rg3d-core/src/pool.rs
- src/scene/graph.rs
This finishes my changes to pool as discussed in #242
- Some docs improvements
- Simplified some code a bit and removed more `as` conversions
> More pool improvements

- src/renderer/shadow/mod.rs
- src/scene/base.rs
- src/scene/visibility.rs
Hi,
Not sure disabling frustum culling will be the right solution in my case, but here is a pr in case you are interested.
Still a bit wip
Not tested much in depth
Haven't added any kind of automated tests (is there any anyway ?)
Also, where should doc for this field by added ?
> Allow disabling frustum_culling

- editor/src/scene/commands/camera.rs
- editor/src/scene/commands/collider.rs
- editor/src/scene/commands/collider2d.rs
- editor/src/scene/commands/decal.rs
- editor/src/scene/commands/effect.rs
- editor/src/scene/commands/graph.rs
- editor/src/scene/commands/joint.rs
- editor/src/scene/commands/joint2d.rs
- editor/src/scene/commands/light.rs
- editor/src/scene/commands/lod.rs
- editor/src/scene/commands/mesh.rs
- editor/src/scene/commands/mod.rs
- editor/src/scene/commands/particle_system.rs
- editor/src/scene/commands/rectangle.rs
- editor/src/scene/commands/rigidbody.rs
- editor/src/scene/commands/rigidbody2d.rs
- editor/src/scene/commands/sound.rs
- editor/src/scene/commands/sound_context.rs
- editor/src/scene/commands/sprite.rs
- editor/src/scene/commands/terrain.rs
PR for #281. If it looks right, I can change all the files using `define_node_command!` to use `define_swap_command!`.
`light.rs` will be:
```rust
define_swap_command! {
Node::as_light_mut,
SetLightScatterCommand(Vector3<f32>): scatter, set_scatter, "Set Light Scatter";
SetLightScatterEnabledCommand(bool): is_scatter_enabled, enable_scatter, "Set Light Scatter Enabled";
SetLightIntensityCommand(f32): intensity, set_intensity, "Set Light Intensity";
SetLightCastShadowsCommand(bool): is_cast_shadows, set_cast_shadows, "Set Light Cast Shadows";
SetLightColorCommand(Color): color, set_color, "Set Light Color";
}
fn node_as_spot_mut(node: &mut Node) -> &mut SpotLight {
node.as_light_mut().as_spot_mut()
}
define_swap_command! {
node_as_spot_mut,
SetSpotLightHotspotCommand(Vector3<f32>): …
```
> First command macro polish #281

- .github/workflows/audit.yml
One new ignore, remove 3 existing ones. I updated the tracking issue - more
details there: https://github.com/FyroxEngine/Fyrox/issues/208
> Update cargo audit CI

- fyrox-ui/README.md
not the best screenshots but something
> working screenshots

- editor/src/interaction/gizmo/move_gizmo.rs
- editor/src/interaction/move_mode.rs
- editor/src/interaction/plane.rs
- fyrox-ui/src/lib.rs
* adds a new "sphere" to the move gizmo
* dragging the sphere moves the object center with collision detection against other objects
> Ability to move around object with collision detection

- template/src/main.rs
hastly made through githubs interface. Having checked if it compiled as a result. Should at least give you a start though :)
> add a bit more information to panic on writing file

- template/src/main.rs
made an error Enum and a function to check the name + some pretty simple display code.
> potential solution to template crashing on encountering reserved names

- fyrox-ui/src/ttf.rs
This supersedes  https://github.com/FyroxEngine/Fyrox/pull/465 which I closed
> Changes to fyrox-ui/src/ttf.rs so it doesn't fail on glyph packing- cleaned up some

- fyrox-ui/src/lib.rs
- fyrox-ui/src/nine_patch.rs
- fyrox-ui/src/ttf.rs
I avoid getting the size of the texture by having the uv's manually set. this also allow you to stretch the texture in margins if you want.
> Added a nine patch widget

- fyrox-core/src/color.rs
Hi.
I added some tests for `color.rs`.
Code coverage for this file now is nearly 100%.
> test: color module

- fyrox-core/src/color_gradient.rs
Code coverage for this file now is 100%.
> test: color gradient

- fyrox-core/src/curve.rs
Code coverage for `curve.rs` now is 100%.
> test: curve

- template/src/main.rs
Add more content at .gitignore template, for a better project-init experience.
> Fyrox template improvements

- fyrox-core/src/math/plane.rs
Code coverage for this file now is 100%.
> test: plane

- template/src/main.rs
> Clarified error message when template init name starts with a number

- editor/src/lib.rs
> Fixed crash in the editor on Wayland

- editor/src/lib.rs
- editor/src/scene/mod.rs
- src/scene/camera.rs
- src/scene/debug.rs
Added a pyramid to visualize the camera's view direction
> Camera's view pyramid visualized

- editor-standalone/Cargo.toml
- editor-standalone/src/main.rs
This I believe saves lots of time when debugging editor functionality.
> Add project dir and scenes to open as cli args to editor

- editor/src/asset/mod.rs
> Prevent moving a folder into its own subfolder.

- .github/workflows/audit.yml
- .github/workflows/ci.yml
> fix: usage of `deprecated` version of `Nodejs`

- fyrox-impl/src/scene/terrain/geometry.rs
- fyrox-impl/src/scene/terrain/mod.rs
- fyrox-impl/src/scene/terrain/quadtree.rs
I have studied the terrain module to better learn how it works and added extended documentation to all the places that puzzled me while I was trying to learn it. I hope that this can be a stepping stone toward further improvements to the terrain, including the addition of holes.
> Expanding the documentation for scene::terrain

- fyrox-animation/src/lib.rs
- fyrox-animation/src/spritesheet/mod.rs
// TODO: Make this configurable.
add max_event_capacity for Animation。
> feat: Maximum capacity for configuring events

- editor/src/asset/mod.rs
https://github.com/notify-rs/notify/issues/645
> fix crash on MacOS in `notify` crate when path is set first time with "Default::default"

- editor/src/scene_viewer/mod.rs
- fyrox-ui/src/tab_control.rs
I have modified TabControl to fix the issue of the first tab always appearing to be selected, and to introduce the concept of identifying tabs by UUID. This should not cause anything to break, but I have modified SceneViewer to use the new UUID system because it is safer to identify tabs by UUID in any situation where tabs are moving due to adding and removing tabs.
I have preserved the position-based tab system unchanged because it is still very useful in any situation where tabs are never added or removed, so tab index makes perfect sense as a way to identify a tab.
> TabControl improvement: fixing a glitch and adding tab UUID.

- project-manager/src/manager.rs
- project-manager/src/utils.rs
Closes https://github.com/FyroxEngine/Fyrox/issues/738
> Print total size of a project in the project manager

- fyrox-ui/src/dock/tile.rs
- fyrox-ui/src/window.rs
I have adjusted the way the minimize button works so that it more closely resembles how it was intended to work. This involved some changes to `Window`, but most of the adjustments are in `Tile` in order to allow minimize and maximize to work seamlessly with the docking system.
* I created `WindowSizeState` and `Window::size_state` to keep track of whether a window is minimized, maximized, or normal. I created a new private method `update_size_state` for managing the transition from one size state to another.
* Maximizing a docked window undocks the window before maximizing it.
* Minimizing a docked window causes the window to shrink into the top or bottom of the parent split tile, thus allowing the other child of that tile to take up most of the space.
* The tile splitter widget no …
> Fixing Window minimize button

- editor/src/plugins/inspector/editors/script.rs
The `fetch_script_definitions` function served to access the environment through the `UserInterface` by getting the `Inspector` widget of the editor and getting the context from the `Inspector`. The issue with this is that when there is no script then the context would be the default context, and the default context has `None` for the environment.
All of this was pointless since `fetch_script_definitions` was called from a place that already has the environment, making all that complexity pointless.
I have removed the `fetch_script_definitions` function and instead called `create_items` directly, thereby avoiding the possibility of failing due to the environment being None.
> Correcting how ScriptPropertyEditorDefinition accesses environment

- fyrox-impl/src/scene/collider.rs
`BitMask` can be easier to read by replacing its raw number with either a 8-digit hexadecimal or a display of each bit of the mask in groups of 8, with bit 0 on the left, just as in the editor. This can be helpful for people who are trying to debug collision issues.
> Implementing `Debug` and `Display` for `BitMask`

- fyrox-ui/src/screen.rs
The only way to do UI scaling that I found was the way the editor is doing it, by setting the render transform on the UI root grid. This method also requires updating the grid width and height every time the window size changes.
Using the `Screen` widget is really convenient, but it is incompatible with the previously mentioned method of UI scaling. The UI always ends up double the window size and going out of bounds of the window. 
This made me decide to implement the UI scaling inside the `Screen` widget, which also seemed like an appropriate place to handle this. Automatic scaling can be turned on and off with a checkbox.
https://github.com/user-attachments/assets/cacac42f-6386-4f3e-986a-78861b4bded9
----
The implementation is not quite perfect. I would have preferred to update the …
> Handle UI scaling in Screen Widget

- fyrox-impl/src/engine/executor.rs
Adds a call to `std::thread::sleep` in the headless executer to reduce CPU load when the game loop is actually idle.
Fixes #761 
I tested this on macOS 15.2, Fedora 38 and Window 11 (VM). On all platforms, CPU load came down from 99% (single core).
| OS | CPU Load |
|-------------|-----------|
| Fedora 38    | 2% - 6% |
| macOS 15.2 | ~ 2% |
| Windows 11  | ~ 2% |
The final elapsed time never exceeded the expected time step of `0.016` on all platforms. ~~I left some debug print statements in the changes for now, to make it easier to verify the timings.~~
Write here.
> Thread sleep in headless executor

- editor/src/camera/mod.rs
- editor/src/scene/mod.rs
- editor/src/settings/camera.rs
* Added a setting to modify the editor camera's mouse sensitivity.
* Updated camera mouse handling code to use `clamp` instead of `if` statements
Fixes #(issue number)
Write here.
Write here.
https://github.com/user-attachments/assets/c91f4fad-2a74-4d99-bc77-b3c544012dff
> Added a setting to modify the editor camera's mouse sensitivity

- fyrox-core/src/visitor/error.rs
- fyrox-core/src/visitor/impls.rs
- fyrox-core/src/visitor/mod.rs
- fyrox-core/src/visitor/pod.rs
Just a little bit more informative warning
> add details to FieldTypeDoesNotMatch error

- fyrox-core/src/visitor/mod.rs
- fyrox-impl/src/engine/mod.rs
- fyrox-impl/src/script/mod.rs
necessary for scripting languages
> dynamically typed script messages
